---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(ggh4x)

library(scales)
library(ggtext)

library(cowplot)

library(patchwork)
library(pals)
```


```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
df_surg_dem <- readRDS("../df/dem/df_surg_dem_reg")
```

```{r}
df_inj_dem <- readRDS("../df/dem/df_inj_dem_reg")
```


```{r}
df_surg_dem %>% count(YEAR_str)
```

```{r}
df_surg_dem %>% filter(is.na(TOTAL)) %>% nrow()
```


```{r}
df_surg_dem %>% count(SHEET, YEAR_str)
```

```{r}
df_surg_dem_total <- df_surg_dem %>%
  distinct(FILE, SHEET, PRO_code, .keep_all = TRUE) %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
  
```

```{r}
df_inj_dem_total <- df_inj_dem %>%
  distinct(FILE, SHEET, PRO_code, .keep_all = TRUE) %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
```



# hepatectomy

```{r}
 df_surg_dem_total %>% filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(CLASS_code)
```


```{r}
df_hptc <- df_surg_dem_total %>% 
  filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        )) %>%
  group_by(YEAR, LOC, TX) %>%
  summarise(SUM = sum(TOTAL)) %>%
  ungroup()
```

```{r}
tsbl_hptc <- df_hptc  %>%
  group_by(YEAR, TX) %>%
  summarise(SUM = sum(SUM)) %>%
  bind_rows(df_hptc %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(SUM)) %>%
              mutate(TX = "All")) %>%
  mutate(TX = factor(TX, levels = c("All",
                                    "Open",
                                    "Lap",
                                    "Lap (RA)"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = TX, index = YEAR)
```



```{r}
t1_c <- tsbl_hptc %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "C") %>%
  mutate(LABEL = "Resection")

t1_c
```


```{r}
lm_hspc <- tsbl_hptc %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

#  mutate(est = round(estimate, digit = 0)) %>%
#  mutate(ci_low = estimate + std.error * qnorm(0.025),
#         ci_up = estimate + std.error * qnorm(1-0.025)) %>%
#  mutate(ci_low_label = round(ci_low, digits = 0),
#         ci_up_label = round(ci_up, digits = 0)) %>%
#  mutate(lm_label = round(estimate, digits = 0)) %>%
#  mutate(lm_label = paste0(lm_label, " [",
#                           ci_low_label, ", ",
#                           ci_up_label, "]"))

lm_hspc
```


```{r}
t1_c <- t1_c %>%
  left_join(lm_hspc %>% select(TX, estimate, std.error),
            by = join_by(TX))


t1_c
```



```{r}
p1_c <- tsbl_hptc %>%
  ggplot()+
  geom_line(aes(YEAR, SUM, group = TX, colour = TX),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = TX),
             size = 1)+
   scale_colour_manual(values = c("#ff7f0e",
                                 "#1f77b4",
                                 "#d62728",
                                 "#bcbd22"),
                      name = "Resection",
                      labels = c("All",
                                 "Open",
                                 "Laparoscopic",
                                 "Robotic"))+
       guides(colour = guide_legend(nrow = 1))+
  scale_y_continuous(
                     breaks = c(seq(0, 25000, 5000)),
                     limits = c(0, 25000),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  labs(tag = "C",
       x = "Year",
       y = "Resection (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.location = "plot",
        legend.justification = c(0, 0.5),
        legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
    #  legend.key.spacing.y = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_c 
```


```{r}
tsbl_hptc_loc <- df_hptc  %>%
  group_by(YEAR, LOC) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(LOC = factor(LOC, levels = c("Partial",
                                      "Sub_seg",
                                      "One_seg",
                                      "Two_seg_"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = LOC, index = YEAR)
```

```{r}
t1_d <- tsbl_hptc_loc %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "D") %>%
  mutate(LABEL = "Surgical procedure")
```

```{r}
lm_hptc_loc <- tsbl_hptc_loc %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

lm_hptc_loc
```

```{r}
t1_d <- t1_d %>%
  left_join(lm_hptc_loc %>% select(LOC, estimate, std.error),
            by = join_by(LOC)) %>%
  rename(TX = "LOC")
```


```{r}
df_surg_dem_total %>% filter(str_detect(PRO_name, "肝切除術"))%>%   count(PRO_name)
```


```{r}
p1_d <- tsbl_hptc_loc %>%
  ggplot()+
  geom_line(aes(YEAR, SUM, group = LOC, colour = LOC),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = LOC),
             size = 1)+
    scale_colour_manual(values = c("#e377c2",
                                  "#2ca02c",
                                 "#ff7f0e",
                                  "#9467bd" ),
                      name = "Surgical\nprocedure",
                      labels = c("Partial",
                                 "Sub-\nsegment",
                                 "One\nsegment",
                                 "Two or more\nsegments"))+
     guides(colour=guide_legend(nrow=1))+
  scale_y_continuous(
                     breaks = c(seq(0, 12000, 3000)),
                     limits = c(0, 12000),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  labs(#tag = "D",
       x = "Year",
       y = "Resection (n)")+
  theme_classic()+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.justification.bottom = c(1, 0.5),
              legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
      legend.key.spacing.y = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_d
```


```{r}
# open

tsbl_hptc_open <- df_hptc  %>%
  filter(TX == "Open") %>%
  group_by(YEAR, LOC) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(LOC = factor(LOC, levels = c("Partial",
                                      "Sub_seg",
                                      "One_seg",
                                      "Two_seg_"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = LOC, index = YEAR)
```


```{r}
p1_e <- tsbl_hptc_open %>%
  ggplot() +
  geom_line(aes(YEAR, SUM, group = LOC, colour = LOC),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = LOC),
             size = 1)+
    scale_colour_manual(values = c("#e377c2",
                                  "#2ca02c",
                                 "#ff7f0e",
                                  "#9467bd"),
                   #   name = "Open\nsurgery",
                      labels = c("Partial",
                                 "Sub-\nsegment",
                                 "One\nsegment",
                                 "Two or more\nsegments"))+
   guides(colour=guide_legend(nrow=1))+
  scale_y_continuous(breaks = seq(0, 8000, 2000),
                     limits = c(0, 8000),
                     label = scales::label_comma())+
  theme_classic()+
    labs(tag = "D",
         #title = "Open surgery",
       x = "Year",
       y = "Open surgery (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.justification.bottom = c(1, 0.5),
       # legend.position = c(1/3, 0),
        legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_e 
```

```{r}
t1_e <- tsbl_hptc_open %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "E") %>%
  mutate(LABEL = "Open surgery")
```

```{r}
lm_hptc_open <- tsbl_hptc_open %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

lm_hptc_open
```

```{r}
t1_e <- t1_e %>%
  left_join(lm_hptc_open %>% select(LOC, estimate, std.error),
            by = join_by(LOC)) %>%
  rename(TX = "LOC")
```



```{r}
# LAP

tsbl_hptc_lap <- df_hptc  %>%
  filter(TX == "Lap") %>%
  group_by(YEAR, LOC) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(LOC = factor(LOC, levels = c("Partial",
                                      "Sub_seg",
                                      "One_seg",
                                      "Two_seg_"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = LOC, index = YEAR)
```

```{r}
cols25()
```


```{r}
p1_f <- tsbl_hptc_lap %>%
  ggplot() +
  geom_line(aes(YEAR, SUM, group = LOC, colour = LOC),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = LOC),
             size = 1)+
    scale_colour_manual(values = c("#e377c2",
                                  "#2ca02c",
                                 "#ff7f0e",
                                  "#9467bd"),
                  #    name = "Laparoscopic\nsurgery",
                      labels = c("Partial",
                                 "Sub-\nsegment",
                                 "One\nsegment",
                                 "Two or more\nsegments"))+
   guides(colour=guide_legend(nrow=1))+
  scale_y_continuous(breaks = seq(0, 6000, 2000),
                     limits = c(0, 6000),
                     label = scales::label_comma())+
  theme_classic()+
    labs(#tag = "F",
         #title = "Laparoscopy",
       x = "Year",
       y = "Laparoscopic surgery (n)")+
  theme_classic()+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.justification.bottom = c(1, 0.5),
        legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_f
```

```{r}
# calculate proprotion

p1_g <- df_hptc %>%
  group_by(YEAR, LOC) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  mutate(TX = case_when(TX == "Lap" ~ "Laparoscopic",
                        TX == "Lap (RA)" ~ "Robotic",
                        .default = TX)) %>%
  mutate(TX = factor(TX,
                     levels = c("Open", "Robotic", "Laparoscopic"))) %>%
  mutate(LOC = case_when(LOC == "Sub_seg" ~ "Subsegment",
                         LOC == "One_seg" ~ "One segment",
                         LOC == "Two_seg_" ~ "Two or more segments",
                         .default = LOC)) %>%
  mutate(LOC = factor(LOC, levels = c("Partial",
                                      "Subsegment",
                                      "One segment",
                                      "Two or more segments"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, PCT, fill = TX))+
  geom_col(width = 0.5, position = "stack")+
  scale_fill_manual(values = c( "#1f77b4",
                                "#d62728",
                                 "#bcbd22"),
                    name = "Resection",
                    breaks = c("Open",
                               "Laparoscopic",
                               "Robotic"))+
  facet_wrap2(vars(LOC), nrow = 1,
              axes = "all",
              remove_labels = "all")+
  scale_y_continuous(expand = c(0, 0))+
 # guides(fill =  guide_legend(override.aes = list(linewidth = 0.1,
#                                                  colour = "black") ) )+
  
  labs(tag = "E",
       x = "Year", y = "Proportion (%)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text.x = element_text(size = 8, colour = "black", face = "bold"),
        strip.text.y = element_blank(),
        axis.title =  element_text(size = 8, colour = "black", face = "bold"),
     #   axis.title.y =  element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x =  element_text(size = 8, colour = "black", angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y =  element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        
        legend.title = element_blank(),
        legend.text =  element_text(size = 8, colour = "black"),  
        legend.position = "bottom",
       # legend.position.inside = c(0.02, 1),
       # legend.justification.inside = c(0, 1),
        legend.direction = "horizontal",
        legend.background = element_blank(),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"),
       legend.key.spacing.y = unit(0, "mm"),
        legend.key.size = unit(4, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0,0,0,0, unit = "mm")
        )

p1_g 
```



```{r}
t1_f <- tsbl_hptc_lap %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "F") %>%
  mutate(LABEL = "Laparoscopic surgery")
```

```{r}
lm_hptc_lap <- tsbl_hptc_lap %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

lm_hptc_open
```

```{r}
t1_f <- t1_f %>%
  left_join(lm_hptc_lap %>% select(LOC, estimate, std.error),
            by = join_by(LOC)) %>%
  rename(TX = "LOC")
```


```{r}
tsbl_hptc_ra <- df_hptc  %>%
  filter(TX == "Lap (RA)") %>%
  group_by(YEAR, LOC) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(LOC = factor(LOC, levels = c("Partial",
                                      "Sub_seg",
                                      "One_seg",
                                      "Two_seg_"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = LOC, index = YEAR)
```

```{r}
tsbl_hptc_ra %>%
  ggplot(aes(YEAR, SUM, group = LOC, colour = LOC)) +
  geom_line()+
  scale_y_continuous(breaks = seq(0, 1000, 500),
                     limits = c(0, 1000))+
  theme_classic()+
  geom_point()
```


```{r}
df_hptc  %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(TX = "Total") %>%
  bind_rows(df_hptc ) %>%
  mutate(TX = factor(TX, levels = c("Total",
                                    "Open",
                                    "Lap",
                                    "Lap (RA)"))) 
```


# RFA 
```{r}
df_abl <- df_surg_dem_total %>% 
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
      mutate(TX = case_when(str_detect(PRO_name, "ラジオ") & str_detect(PRO_name, "腹腔鏡") ~ "RFA (Lap)",
                            str_detect(PRO_name, "ラジオ") & !str_detect(PRO_name, "腹腔鏡") ~ "RFA",
                            str_detect(PRO_name, "マイクロ") & str_detect(PRO_name, "腹腔鏡") ~ "MWA (Lap)",
                            str_detect(PRO_name, "マイクロ") & !str_detect(PRO_name, "腹腔鏡") ~ "MWA")) %>%
  group_by(YEAR, TX) %>%
  summarise(SUM = sum(TOTAL))
```

```{r}
tsbl_abl_all <- df_abl %>%
  mutate(TX = case_when(str_detect(TX, "RFA") ~ "RFA",
                        str_detect(TX, "MWA") ~ "MWA",
                        .default= TX)) %>%
  group_by(YEAR, TX) %>%
  summarise(SUM = sum(SUM)) %>%
  bind_rows(df_abl %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(SUM)) %>%
              mutate(TX = "All")) %>%
  mutate(TX = factor(TX, levels = c("All",
                                    "RFA",
                                    "MWA")))  %>%
  mutate(YEAR = as.numeric(YEAR))  %>%
  as_tsibble(key = TX, index = YEAR)
```

```{r}
tsbl_abl <- df_surg_dem_total %>%
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(TX = "All") %>%
  bind_rows(df_abl) %>%
  mutate(TX = factor(TX, levels = c("All",
                                    "RFA",
                                    "RFA (Lap)",
                                    "MWA",
                                    "MWA (Lap)")))  %>%
  mutate(YEAR = as.numeric(YEAR))  %>%
  as_tsibble(key = TX, index = YEAR)
```

```{r}
# calculate proportion of lap/per

df_abl %>%
  mutate(APP = case_when(str_detect(TX, "Lap") ~ "Lap",
                         .default = "Percu")) %>%
  group_by(YEAR, APP) %>%
  summarise(SUM = sum(SUM)) %>%
  ungroup() %>%
  group_by(YEAR) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  arrange(desc(PCT))
```

```{r}
# calculate proportion of lap/per

df_abl %>%
  mutate(APP = case_when(str_detect(TX, "RFA") ~ "RFA",
                         .default = "MWA")) %>%
  group_by(YEAR, APP) %>%
  summarise(SUM = sum(SUM)) %>%
  ungroup() %>%
  group_by(YEAR) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  arrange(desc(PCT))
```


```{r}
# calculate proportion of lap/per

df_abl %>%
  group_by(YEAR) %>%
  mutate(ALL = sum(SUM)) %>%
  
  mutate(PCT = SUM/ALL * 100) %>%
  arrange(desc(PCT))
```

```{r}
df_abl %>%
  group_by(YEAR) %>%
  mutate(ALL = sum(SUM)) %>%
  
  mutate(PCT = SUM/ALL * 100) %>%
  arrange(desc(PCT)) %>%
  filter(YEAR == "2023")
```

```{r}
p1_b <- tsbl_abl %>%
  ggplot()+
  geom_line(aes(YEAR, SUM, group = TX, colour = TX),
            linewidth = 0.3)+
  geom_point(aes(YEAR, SUM, colour = TX),
             size = 1)+
  scale_colour_manual(values = c("#2ca02c",
                                 "#e377c2",
                                 "#8c564b",
                                 "#17becf",
                                 "#7f7f7f"),
                      name = "Ablation")+
     guides(colour=guide_legend(nrow=1))+
  scale_y_continuous(breaks = seq(0, 25000, 5000),
                     limits = c(0, 25000),
                     labels = label_comma()
                     )+
  labs(tag = "B",
       x = "Year",
       y = "Ablation (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
      #  plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text  = element_text(size = 8, colour = "black"),
      legend.position = "bottom",
      legend.justification = c(1, 0.5),
      legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
 #     legend.key.spacing.y = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_b
```


```{r}
t1_b <- tsbl_abl %>%
  group_by_key(TX) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "B") %>%
  mutate(LABEL = "Ablation")
```

```{r}
lm_abl <- tsbl_abl %>%
  group_by_key(LOC) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

lm_abl
```

```{r}
t1_b <- t1_b %>%
  left_join(lm_abl %>% select(TX, estimate, std.error),
            by = join_by(TX)) 
```


# TACE and TAI

```{r}
df_inj_dem_total %>% filter(str_detect(CLASS_name, "動注"))
```


```{r}
df_inj_dem_total %>% filter(str_detect(PRO_name, "肝動脈")) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(TX = "p") %>%
  ggplot(aes(YEAR, SUM, group = TX))+
  geom_line(linewidth = 0.3) +
  geom_point()+
  scale_y_continuous(breaks = seq(0, 3000, 1000),
                     limits = c(0, 3000))+
  labs(x = "Year",
       y = "Count",
       title = "TACE")+
  theme_classic()+
  theme(plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"))
```

```{r}
df_surg_dem_total %>% filter(
                       (str_detect(PRO_name, "化学塞栓") )) %>%
  count(PRO_name) %>% View()
```


```{r}
df_surg_dem_total %>% filter(
                       (str_detect(PRO_name, "化学塞栓") )) %>%
    group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(TX = "p") %>%
  ggplot(aes(YEAR, SUM, group = TX))+
  geom_line(linewidth = 0.3) +
  geom_point()+
  scale_y_continuous(breaks = seq(0, 50000, 10000),
                     limits = c(0, 50000))+
  labs(x = "Year",
       y = "Count",
       title = "TACE")+
  theme_classic()+
  theme(plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"))
```

```{r}
tsbl_tace <- df_surg_dem_total %>% filter(
                       (str_detect(PRO_name, "化学塞栓") )) %>%
    group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(TX = "TACE") %>%
  mutate(YEAR = as.numeric(YEAR))  %>%
  as_tsibble(key = TX, index = YEAR)
```



```{r}
tsbl_comb <- tsbl_hptc %>%
  filter(TX =="All") %>%
  mutate(TX ="Resection") %>%
  bind_rows(tsbl_abl %>% filter(TX == "All") %>% mutate(TX = "Ablation")) %>%
  bind_rows(tsbl_tace) %>%
  mutate(TX = factor(TX, levels = c("Resection",
                                    "Ablation",
                                    "TACE")))
```



```{r}
p1_a <- tsbl_comb %>%
  ggplot(aes(YEAR, SUM, group = TX, colour = TX))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  scale_colour_manual(values = c("#ff7f0e",
                                 "#2ca02c",
                                 "#9467bd"),
                     name = "Treatment")+
  
  scale_y_continuous(limits = c(0, 50000),
                     breaks = seq(0, 50000, 10000),
                     labels = scales::label_comma())+
    labs(tag = "A",
       x = "Year",
       y = "Treatment (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
      #  plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text  = element_text(size = 8, colour = "black"),
      legend.position = "bottom",
      legend.location = "plot",
      legend.justification = c(0, 0.5),
      legend.margin = margin(0, 0, 0, 0, "mm"),
      legend.box.spacing = unit(0, "mm"),
      plot.margin = margin(0,0,0,0, "mm"))

p1_a
```


```{r}
t1_a <- tsbl_comb %>%
  group_by_key(TX) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(FIG = "A") %>%
  mutate(LABEL = "Treatment")
```

```{r}
lm_comb <- tsbl_comb %>%
  group_by_key(TX) %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR")

lm_comb
```

```{r}
t1_a <- t1_a %>%
  left_join(lm_comb %>% select(TX, estimate, std.error),
            by = join_by(TX)) 
```

```{r}
t1 <- t1_a %>%
  bind_rows(t1_b) %>%
  bind_rows(t1_c) %>%
  bind_rows(t1_d) %>%
  bind_rows(t1_e) %>%
  bind_rows(t1_f) 

t1 
```

```{r}
t1 <- t1 %>%
  relocate(FIG, .before = "TX") %>%
  relocate(LABEL, .after = "FIG")

t1
```

```{r}
#  add statistics
t1 <- t1 %>%
  mutate(est = round(estimate, digit = 0)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  
  mutate(ci_low_label = case_when(abs(ci_low) < 10 & abs(ci_low) > 5 ~ round(ci_low, digits = 1) %>% format(nsmall = 1),
                          abs(ci_low) <= 5 ~ round(ci_low, digits = 2) %>% format(nsmall = 2),
                          .default = round(ci_low, digits = 0) %>% comma() %>% format(nsmall = 0))) %>%
  
  mutate(ci_up_label = case_when(abs(ci_up) < 10 & abs(ci_up) > 5 ~ round(ci_up, digits = 1) %>% format(nsmall = 1),
                          abs(ci_up) <= 5 ~ round(ci_up, digits = 2) %>% format(nsmall = 2),
                          .default = round(ci_up, digits = 0) %>% comma() %>% format(nsmall = 0))) %>%
  
  mutate(beta = case_when(abs(estimate) < 10 & abs(estimate) > 5 ~ round(estimate, digits = 1) %>% format(nsmall = 1),
                          abs(estimate) <= 5 ~ round(estimate, digits = 2) %>% format(nsmall = 2),
                          .default = round(estimate, digits = 0) %>% comma() %>% format(nsmall = 0))) %>%
  
  mutate(across(c(starts_with("ci"), beta), ~ str_remove_all(.x, "\\s"))) %>%
  
  mutate(ci_95 = paste0( "[",
                           ci_low_label, ", ",
                           ci_up_label, "]"))

t1 %>% View()
```


```{r}
df_all <- tsbl_comb %>% mutate(FIG = "A") %>% as_tibble() %>%
  bind_rows(tsbl_abl %>% mutate(FIG = "B") %>% as_tibble()) %>%
  bind_rows(tsbl_hptc %>% mutate(FIG = "C") %>% as_tibble()) %>%
  bind_rows(tsbl_hptc_loc %>% mutate(FIG = "D") %>% as_tibble() %>% rename(TX = "LOC")) %>%
  bind_rows(tsbl_hptc_open %>% mutate(FIG = "E") %>% as_tibble() %>% rename(TX = "LOC")) %>%
  bind_rows(tsbl_hptc_lap %>% mutate(FIG = "F") %>% as_tibble() %>% rename(TX = "LOC"))

df_all
```


```{r}
df_dif <- df_all %>%
  ungroup() %>%
  filter(YEAR %in% c(2014, 2023)) %>%
  mutate(ID = paste0(FIG, "_", TX)) %>%
  mutate(COL = paste0("y_", YEAR)) %>%
  select(ID, COL, SUM) %>%
  pivot_wider(names_from = COL,
              values_from = SUM) %>%
  mutate(DIF = y_2023 - y_2014) %>%
  mutate(PCT = DIF/y_2014 * 100) %>%
  mutate(PCT = case_when(abs(PCT) >= 10 ~ round(PCT, digit = 0) %>% as.character(),
                         abs(PCT) < 10 ~ round(PCT, digit = 1) %>% as.character()))

df_dif
```

```{r}
t1 <- t1 %>%
  mutate(ID = paste0(FIG, "_", TX)) %>%
  left_join(df_dif, by = join_by(ID))
```


```{r}
t1 %>% View()
```

```{r}
colnames(t1)
```

```{r}
t1 %>%
  select(FIG, LABEL, TX, adj_r_squared, p_value, beta, ci_95) %>%
  group_by(FIG) %>%
  mutate(RN = row_number()) %>%
  ungroup() %>%
  mutate(FIG = case_when(RN == 1 ~ FIG)) %>%
  mutate(LABEL = case_when(RN == 1 ~ LABEL)) %>%
  View()
```


```{r}
t1_mod <- t1 %>%
  select(FIG, LABEL, TX, adj_r_squared, p_value, beta, ci_95) %>%
  group_by(FIG) %>%
  mutate(RN = row_number()) %>%
  ungroup() %>%
  mutate(FIG = case_when(RN == 1 ~ FIG)) %>%
  mutate(LABEL = case_when(RN == 1 ~ LABEL))

#t1_mod %>% View()
```


```{r}
t1_mod <- t1_mod %>%
  select(FIG, LABEL, TX, adj_r_squared, p_value, beta, ci_95) %>%
  group_by(FIG) %>%
  mutate(RN = row_number()) %>%
  ungroup() %>%
  mutate(FIG = case_when(RN == 1 ~ FIG)) %>%
  mutate(LABEL = case_when(RN == 1 ~ LABEL)) %>%
  mutate(r2 = formatC(adj_r_squared, digits = 2, format = "fg", flag = "#" ))

t1_mod %>% View()
```


```{r}
get_exp <- function(x){

  # if na return ""
  
  if(is.nan(x) | x > 0.001){
    return("")
  }
  
  else {
    
    p <- formatC(x, digits = 2, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    
    return(ex)
    }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){
  
  if (is.nan(x)){
      return("NA")
    }
  
  else if (x > 0.001) {
    p <- formatC(x, digits = 2, format = "fg", flag = "#")
    
    return(p)
  }
  
  else{
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
symbol_p <- function(x){
  if (is.nan(x)){
    return("")
  }
  else if (x < 0.001){
    return("***")
    }
  else if (x < 0.01){
    return("**")
  }
  else if (x < 0.05){
    return("*")
  }
  else {
    return("")
  }
}

symbol_pv <- Vectorize(symbol_p)
```


```{r}
#t1_mod <- 
wb_1 <-  t1_mod %>%
  mutate(p_exp = get_expv(p_value)) %>%
  mutate(p_num = get_numv(p_value)) %>%
  
  mutate(across(c(beta, ci_95, p_exp), ~ str_replace_all(.x, "-", "−"))) %>%
  
  mutate(p = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript")) 
    }) ) %>%
  mutate(p_symbol = symbol_pv(p_value))

wb_1 
```



```{r}
wb_1 <- wb_1 %>%
  select(FIG, LABEL, TX, beta, ci_95, p, p_symbol, r2) %>%
  mutate(TX = case_when(str_detect(TX, "RA") ~ "Robotic",
                        .default = TX)) %>%
  mutate(TX = str_replace(TX, "Lap", "Laparoscopic")) %>%
  mutate(TX = case_when(str_detect(TX, "Sub_seg") ~ "Subsegment",
                        str_detect(TX, "One_seg") ~ "One segment",
                        str_detect(TX, "Two_seg_") ~ "Two or more segments",
                        .default = TX))
```

```{r}
wb_1  <- wb_1 %>%
  mutate(beta = case_when(TX == "Robotic" ~ "NA",
                          .default = beta)) %>%
  mutate(ci_95 = case_when(TX == "Robotic" ~ "NA",
                          .default = ci_95)) %>%
  mutate(r2 = case_when(TX == "Robotic" ~ "NA",
                          .default = r2))
```

```{r}
wb_1 <- wb_1  %>%
  mutate(across(everything(), ~ replace_na(.x, "")))
```

```{r}
wb_1  <- wb_1 %>%  
  rename(Procedure = "TX",
         p_value = "p")
```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = wb_1 ) %>%
  wb_save("../table/Table1.xlsx")
```

```{r}
p1_ef <- p1_e + p1_f + plot_layout(guides = "collect")&
  theme(legend.position = "bottom")

p1_ef
```



```{r}
p1 <- p1_a + p1_b +
  p1_c + p1_d +
  p1_e + p1_f+ 
  p1_g  +
  plot_layout(design = "
              AB
              AB
              AB
              AB
              CD
              CD
              CD
              CD
              EF
              EF
              EF
              EF
              GG
              GG
              GG")&
  theme(legend.box.spacing = unit(1, "mm"))

p1 
```

```{r}
ggsave("../figure/Fig1.pdf", p1,
       width = 175, height = 235, units = "mm")
```


# save 1
