---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(rkt)

library(scales)
library(glue)
library(ggtext)
library(patchwork)

library(cowplot)
library(pals)

library(ggh4x)

library(pals)
```


```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
df_surg_dem <- readRDS("../df/dem/df_surg_dem_reg")
```

```{r}
df_inj_dem <- readRDS("../df/dem/df_inj_dem_reg")
```

```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```


```{r}
df_surg_dem %>% count(YEAR_str)
```

```{r}
df_surg_dem %>% filter(is.na(TOTAL)) %>% nrow()
```


```{r}
df_surg_dem %>% count(SHEET, YEAR_str)
```

```{r}
df_surg_dem <- df_surg_dem %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
  
```

```{r}
df_inj_dem <- df_inj_dem %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
```

```{r}
df_surg_dem <- df_surg_dem %>%
  mutate(AGE = str_replace_all(AGE, "_", "-"))
```


```{r}
df_surg_dem <- df_surg_dem  %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```


```{r}
# format age

df_surg_dem <- df_surg_dem %>%
    mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-49" = "0-4",
                          "0-49" = "5-9",
                          "0-49" = "10-14",
                          "0-49" = "15-19",
                          "0-49" = "20-24",
                          "0-49" = "25-29",
                          "0-49" = "30-34",
                          "0-49" = "35-39",
                          "0-49" = "40-44",
                          "0-49" = "45-49",
                          "50-59" = "50-54",
                          "50-59" = "55-59",
                          "60-69" = "60-64",
                          "60-69" = "65-69",
                          "70-79" = "70-74",
                          "70-79" = "75-79",
                          "80-" = "80-84",
                          "80-" = "85-89",
                          "80-" = "90-")) 
```


```{r}
levels_age <- df_surg_dem  %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_surg_dem  <- df_surg_dem  %>%
  mutate(AGE = factor(AGE, levels = levels_age))
```


# format pop

```{r}
df_pop_dem_cat <- df_pop_dem %>%
  filter(AGE != "total") %>%
  mutate(AGE = str_remove(AGE, "_")) %>%
  mutate(AGE = as.numeric(AGE)) %>%
  mutate(AGE_cat = case_when(AGE %in% 0:49 ~ "0-49",
                             AGE %in% 50:59 ~ "50-59",
                             AGE %in% 60:69 ~ "60-69",
                             AGE %in% 70:79 ~ "70-79",
                             AGE >= 80 ~ "80-"
                             ))
```


```{r}
df_pop_dem_sa <- df_pop_dem_cat %>%
  group_by(YEAR, AGE_cat) %>%
  summarise(All = sum(ALL_total),
            Male = sum(ALL_m),
            Female = sum(ALL_f)) %>%
  pivot_longer(cols = c(All, Male, Female),
               names_to = "SEX",
               values_to = "POP") %>%
  ungroup()


df_pop_dem_sa  
```

# hepatectomy

```{r}
 df_surg_dem %>% filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(CLASS_code)
```


```{r}
df_hptc <- df_surg_dem %>% filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        ))

df_hptc 
```

# RFA 
```{r}
df_abl <- df_surg_dem %>% 
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
      mutate(TX = case_when(str_detect(PRO_name, "ラジオ") & str_detect(PRO_name, "腹腔鏡") ~ "RFA (Lap)",
                            str_detect(PRO_name, "ラジオ") & !str_detect(PRO_name, "腹腔鏡") ~ "RFA",
                            str_detect(PRO_name, "マイクロ") & str_detect(PRO_name, "腹腔鏡") ~ "MWA (Lap)",
                            str_detect(PRO_name, "マイクロ") & !str_detect(PRO_name, "腹腔鏡") ~ "MWA")) 
```

```{r}
df_abl <- df_abl %>%
  mutate(TX = str_remove(TX, "\\s.+")) %>%
  mutate(TX = factor(TX, levels = c("RFA", "MWA")))
```

# TACE

```{r}
df_tace <- df_surg_dem %>% filter(
  
                       (str_detect(PRO_name, "化学塞栓") )) %>%
  mutate(TX = "TACE")
```

# combine everything

```{r}
df_comb <- df_hptc %>% mutate(TX = "Resection") %>%
  bind_rows(df_abl %>% mutate(TX = "Ablation")) %>%
  bind_rows(df_tace %>% mutate(TX = "TACE")) %>%
  mutate(TX = factor(TX, levels = c("Resection",
                                    "Ablation",
                                    "TACE")))


```


```{r}
df_comb_n <- df_comb %>%
  group_by(SEX, AGE, TX, YEAR) %>%
  summarise(SUM = sum(VALUE)) %>%
  bind_rows(df_comb %>%
              group_by(AGE, TX, YEAR) %>%
              summarise(SUM = sum(VALUE)) %>%
              mutate(SEX = "All")) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female")))  
```

```{r}
tx_liver <- df_comb %>% distinct(TX) %>% pull(TX) %>% as.character()

tx_liver 
```

```{r}
df_comb_n %>%
  group_by(TX) %>%
  slice_max(SUM, n = 1)
```

# time series analysis

```{r}
df_comb_adj <-  df_comb_n %>%
  mutate(ID = paste0(YEAR, "_", SEX, "_", AGE)) %>%
  left_join(df_pop_dem_sa %>%
           mutate(ID = paste0(YEAR, "_", SEX, "_", AGE_cat)) %>%
           select(ID, POP),
         by = join_by(ID)) %>%
  mutate(ADJ = SUM/POP * 10^2) %>%
  select(!ID)
```

```{r}
df_comb_adj_long <- df_comb_adj %>%
  pivot_longer(cols = c(SUM, ADJ),
               values_to = "VALUE",
               names_to = "CAT")
```

```{r}
df_comb_adj_long %>%
  group_by(CAT, TX) %>%
  summarise(max = max(VALUE))
```



```{r}
y_scale_facet <- list(CAT == "SUM" & TX == "Resection" ~ scale_y_continuous(limits = c(0, 9000),
                                                                        breaks = seq(0, 9000, 3000),
                                                                        labels = scales::label_comma()),
             CAT == "SUM" & TX == "Ablation" ~ scale_y_continuous(limits = c(0, 10000),
                                                                         breaks = seq(0, 10000, 2500),
                                                                         labels = scales::label_comma()),
             CAT == "SUM" & TX == "TACE" ~ scale_y_continuous(limits = c(0, 20100),
                                                                           breaks = seq(0, 20000, 5000),
                                                                           labels = scales::label_comma()),
             
             CAT == "ADJ" & TX == "Resection" ~ scale_y_continuous(limits = c(0, 90),
                                                                                              breaks = seq(0, 90, 30)),
             CAT == "ADJ" & TX == "Ablation" ~ scale_y_continuous(limits = c(0, 100),
                                                                                               breaks = seq(0, 100, 25)),
             CAT == "ADJ" & TX == "TACE" ~ scale_y_continuous(limits = c(0, 250),                                                                                          breaks = seq(0, 250, 50))
  )
```

```{r}
convert_strip <- function(x){
  if (x == "SUM"){
    return("**n**")
  }
  
  else if (x == "ADJ"){
    return("**n/10<sup>5</sup> people**")
  }
  
  else {
    return(x)
  }
}

 convert_strip <- Vectorize(convert_strip)
```


```{r}
# redo p1

p1_a <- df_comb_adj_long %>%
  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) %>%
      mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  ggplot(aes(YEAR, VALUE, group = SEX, colour = SEX))+
  geom_line(linewidth = 0.3)+
  
  scale_colour_manual(values = c("black",
                                 "#1f77b4",
                                 "#d62728"),
                      labels = c("Both",
                                 "Male",
                                 "Female"))+
  
  facet_nested(TX + CAT ~ AGE ,
               scales = "free_y",
               switch = "y",
               axes = "all",
               remove_labels = "all",
               nest_line = element_line(colour = "black", linewidth = 0.3),
               labeller = labeller(CAT = convert_strip) )+
  
  ggh4x::facetted_pos_scales(y = y_scale_facet) +
  
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2019, 5))+
  
  guides(colour = guide_legend(override.aes = list(linewidth = 0.5) ) )+

  
  labs(tag = "A",
       x = "Year")+
  
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        strip.placement = "outside",
        strip.text.y.left = element_markdown(size = 8, colour = "black", face = "bold"),
        
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(0.01, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank(),
        legend.key.spacing.y = unit(0, "mm"),
        legend.key.height = unit(1, "line"),
        legend.key = element_rect(#colour = "transparent",
                                  fill = "transparent"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        panel.spacing = unit(2, "mm")
        )
  
  p1_a
```

#p1_c

```{r}
p1_c <- df_comb_adj_long %>%
  filter(SEX == "All" & CAT == "SUM") %>%
  mutate(SEX = str_replace(SEX, "All", "")) %>%
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
    ggplot(aes(YEAR, VALUE, colour = TX, group = TX))+
    geom_line(linewidth = 0.3)+
    scale_colour_manual(values = c("#ff7f0e",
                                 "#2ca02c",
                                 "#9467bd"))+
  facet_nested(SEX + CAT ~ AGE,
              
              remove_labels = "all",
              axes = "all",
              switch = "y",
              labeller = labeller(CAT = convert_strip))+
  
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2019, 5))+
  
   scale_y_continuous(limits = c(0, 20100),
                      breaks = seq(0, 20000, 5000),
                     labels = scales::label_comma())+
   guides(colour = guide_legend(override.aes = list(linewidth = 0.5) ) )+
  labs(tag = "C",
       x = "Year",
       y = "Count (n)")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
          strip.background = element_blank(),
          strip.placement = "outside",
        strip.text.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        strip.text.y.left  = element_markdown(size = 8, colour = "black"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_blank(),
        axis.text.x = element_text( size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(0.01, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank(),
        legend.key.spacing.y = unit(0, "mm"),
        legend.key.height = unit(1, "line"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 2, 0, unit = "mm"),
        panel.spacing = unit(2, "mm")
        )

p1_c
```


# RKT

```{r}
df_comb_adj_long <- df_comb_adj_long %>%
  mutate(ID = paste0(SEX, "_" , AGE, "_", TX, "_", CAT))
```

# add 

```{r}
# man kendall test on raw values


df_comb_adj_rkt <- df_comb_adj_long  %>%

  mutate(YEAR = as.numeric(YEAR)) %>%
  ungroup() %>%
  nest(data = -ID) %>%
  mutate(
    model = purrr::map(data, ~ rkt(date = .x$YEAR,
                                 y = .x$VALUE)),
    tau = map_dbl(model, "tau"),
    p_value = map_dbl(model, "sl"),
    slope = map_dbl(model, "B")
  )

df_comb_adj_rkt

```

```{r}
# split ID

df_comb_res <- df_comb_adj_rkt %>%
  separate_wider_delim(cols = ID,
                       delim = "_",
                       names = c("SEX", "AGE", "TX", "CAT"))

```

```{r}
get_exp <- function(x){
  
  if (x > 0.001){
    return("")
  }
  else{

    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    
    return(ex)
}}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){

   if (x > 0.001){
    
    p <- formatC(x, digits = 2, format = "fg", flag = "#" )
    return(p)
    
   }
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
}}

get_numv <- Vectorize(get_num)
```


```{r}
symbol_p <- function(x){
  if (is.na(x)){
    return(NA)
  }
  
  else if (x < 0.001){
    return("***")
  }
  
  else if (x < 0.01){
    return("**")
  }
  
  else if (x < 0.05) {
    return("*")
  }
  
  else {
   return("")
  }}

symbol_pv <- Vectorize(symbol_p)

```


```{r}
df_comb_res <- df_comb_res %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  mutate(TX = factor(TX, levels = c("Resection", "Ablation", "TACE"))) %>%
  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) %>%
  arrange(TX, AGE, SEX, CAT)

df_comb_res
```

```{r}
df_comb_res <- df_comb_res %>%
  mutate(slope_label = case_when(abs(slope) < 10 ~ formatC(slope, digits = 2, format = "fg", flag = "#"),
                           .default = round(slope) %>% scales::comma())) %>%
  
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
  
  mutate(p_num = get_numv(p_value),
         p_exp = get_expv(p_value)) %>%
  
  mutate(across(c(ends_with("_label"), p_exp), ~ str_replace_all(.x, "-", "−"))) %>%
  
  mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))}) ) %>%

  mutate(p_symbol = symbol_pv(p_value))

df_comb_res
```

```{r}
t1 <- df_comb_res %>%
 select(TX, AGE, SEX, slope_label, tau_label, p_label, p_symbol, CAT) 

```

```{r}
t1_a <- df_comb_res %>%
  filter(CAT == "SUM") %>%
  mutate(ID = paste0(TX, "_", AGE, "_", SEX)) %>%
  select(TX, AGE, SEX, ends_with("_label"), p_symbol, ID)

t1_b <- df_comb_res %>%
  filter(CAT == "ADJ") %>%
  mutate(ID = paste0(TX, "_", AGE, "_", SEX)) %>%
  select(ends_with("label"), p_symbol, ID)
```


```{r}
t1_ab <- t1_a %>%
  left_join(t1_b,
            by = join_by(ID),
            suffix = c("_sum", "_adj")) %>%
  select(TX, AGE, SEX, ends_with("_sum"), ends_with("_adj")) %>%
  mutate(AGE = str_replace_all(AGE, "-", "–"))

t1_ab
```

```{r}
t1_ab <- t1_ab %>%
  rename(Treatment = "TX",
         Age = "AGE",
         Sex = "SEX")
```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t1_ab) %>%
  wb_save("../table/TableS6.xlsx")
```


```{r}
# turn df_comb_res into heatmap

p1_b <- df_comb_res %>%
  
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  
  mutate(label = paste0(tau_label, p_symbol)) %>%
  
  mutate(SEX = str_replace(SEX, "All", "Both")) %>%
  mutate(SEX = factor(SEX, levels = c("Female", "Male", "Both"))) %>%
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) %>%

  ggplot(aes(AGE, SEX, fill = tau))+
  geom_tile(linewidth = 0.3, colour = "black")+
  scale_fill_gradient2(low = "#74add1",
                      mid  = "white",
                      high = "#f46d43",
                      limits = c(-1, 1),
                      name = expression(tau))+
  geom_text(aes(label = label),
            size = 2.8, colour = "black")+
  facet_grid2(rows = vars(TX),
              cols = vars(CAT),
              switch = "y",
              labeller = labeller(CAT = convert_strip))+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  labs(tag = "B",
       x= "Age",
       y = "Treatment")+
  
    coord_cartesian(clip = "off")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.placement = "outside",
        strip.clip = "off",
          strip.background = element_blank(),
          strip.text.x = element_markdown(size = 8, colour = "black", face = "bold",
                                          margin = margin(0, 0, 0, 0, "mm")),
          strip.text.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_blank(),
          
          axis.text = element_text(size = 8, colour = "black"),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          legend.title = element_text(size = 8, colour = "black"),
          legend.text = element_text(size = 8, colour = "black"),
          legend.key.height = unit(1, "lines"),
          legend.key.width = unit(0.75, "lines"),
          plot.margin = margin(0, 0, 0, 0, "mm"),
          legend.margin = margin(0, 0, 0, 0, "mm"))
p1_b
```

# assemble plot

```{r}
# assemble plots

p1 <- p1_a + patchwork::free(p1_b, side = "lr") + p1_c +
  plot_layout(ncol = 1,
              heights = c(6, 2.1, 1))

p1

ggsave("../figure/Fig3.pdf", p1, 
       width = 175, height = 235, units = "mm")
```



```{r}
ggsave("../figure/Fig3.pdf", p1, 
       width = 175, height = 235, units = "mm")
```


