---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(rkt)

library(scales)
library(glue)
library(ggtext)
library(patchwork)

library(cowplot)
library(pals)

library(ggh4x)
```

```{r}
# make df folder

dir.create("../plot", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

#dir.create("../df/long", showWarnings = TRUE, recursive = FALSE, #mode = "0777")
```

```{r}
df_surg_dem <- readRDS("../df/dem/df_surg_dem_reg")
```

```{r}
df_inj_dem <- readRDS("../df/dem/df_inj_dem_reg")
```

```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```

```{r}
df_surg_dem %>% count(YEAR_str)
```

```{r}
df_surg_dem %>% filter(is.na(TOTAL)) %>% nrow()
```


```{r}
df_surg_dem %>% count(SHEET, YEAR_str)
```

```{r}
df_surg_dem <- df_surg_dem %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
  
```

```{r}
df_inj_dem <- df_inj_dem %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(TOTAL = replace_na(TOTAL, 0))
```

```{r}
df_surg_dem <- df_surg_dem %>%
  mutate(AGE = str_replace_all(AGE, "_", "-"))
```


```{r}
df_surg_dem <- df_surg_dem  %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```


```{r}
# format age

df_surg_dem <- df_surg_dem %>%
    mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-39" = "0-4",
                          "0-39" = "5-9",
                          "0-39" = "10-14",
                          "0-39" = "15-19",
                          "0-39" = "20-24",
                          "0-39" = "25-29",
                          "0-39" = "30-34",
                          "0-39" = "35-39",
                        #  "0-49" = "40-44",
                        #  "0-49" = "45-49"
                          )) 
```


```{r}
levels_age <- df_surg_dem  %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_surg_dem  <- df_surg_dem  %>%
  mutate(AGE = factor(AGE, levels = levels_age))
```

# format pop

```{r}
df_pop_dem_cat <- df_pop_dem %>%
  filter(AGE != "total") %>%
  mutate(AGE = str_remove(AGE, "_")) %>%
  mutate(AGE = as.numeric(AGE)) %>%
  mutate(AGE_cat = case_when(AGE %in% 0:49 ~ "0-49",
                             AGE %in% 50:59 ~ "50-59",
                             AGE %in% 60:69 ~ "60-69",
                             AGE %in% 70:79 ~ "70-79",
                             AGE >= 80 ~ "80-"
                             ))
```


```{r}
df_pop_dem_sa <- df_pop_dem_cat %>%
  group_by(YEAR, AGE_cat) %>%
  summarise(All = sum(ALL_total),
            Male = sum(ALL_m),
            Female = sum(ALL_f)) %>%
  pivot_longer(cols = c(All, Male, Female),
               names_to = "SEX",
               values_to = "POP") %>%
  ungroup()


df_pop_dem_sa  
```

# hepatectomy

```{r}
 df_surg_dem %>% filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(PRO_name, CLASS_code)
```


```{r}
 df_surg_dem %>% filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(CLASS_code)
```


```{r}
df_hptc <- df_surg_dem %>% filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        )) %>%
  mutate(TX = factor(TX,
                     levels = c("Open", "Lap", "Lap (RA)"))) %>%
  mutate(LOC = factor(LOC,
                      levels = c("Partial", "Sub_seg", "One_seg", "Two_seg_")))

df_hptc 
```

```{r}
df_hptc %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(AGE, SUM, colour = YEAR, group = YEAR))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = pals::kovesi.rainbow(n=10))+
  facet_grid( cols = vars(SEX), scale = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, size = 8, colour = "black"))
```



```{r}
df_hptc %>%
  mutate(TX = str_remove(TX, "\\s\\(RA\\)")) %>%
  mutate(TX = factor(TX, levels  = c("Open",
                                     "Lap"))) %>%
  group_by(YEAR, SEX, AGE, TX) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(AGE, SUM, colour = YEAR, group = YEAR))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = pals::kovesi.rainbow(n=10))+
  facet_grid(rows = vars(TX), cols = vars(SEX), scale = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, size = 8, colour = "black"))
```

```{r}
df_hptc %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR, SUM, colour = SEX, group = SEX))+
  geom_line(linewidth = 0.3)+
 # scale_colour_manual(values = pals::kovesi.rainbow(n=10))+
  facet_wrap2(vars(AGE), scale = "free_y", ncol = 6)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        legend.position = "none")
```

```{r}
df_hptc %>%
  group_by(SEX, AGE, TX) %>%
  summarise(SUM = sum(VALUE))
```


```{r}
df_hptc_tx <- df_hptc %>%
  mutate(AGE = fct_recode(AGE,
                          "0-49" = "0-39",
                          "0-49" = "40-44",
                          "0-49" = "45-49",
                          "50-59" = "50-54",
                          "50-59" = "55-59",
                          "60-69" = "60-64",
                          "60-69" = "65-69",
                          "70-79" = "70-74",
                          "70-79" = "75-79",
                          "80-" = "80-84",
                          "80-" = "85-89",
                          "80-" = "90-")) %>%
  group_by(YEAR, SEX, AGE, TX) %>%
  summarise(SUM = sum(VALUE)) 
```

```{r}
df_hptc_tx <- df_hptc_tx  %>%
  bind_rows(df_hptc_tx %>%
              group_by(YEAR, AGE, TX) %>%
              summarise(SUM = sum(SUM)) %>%
              mutate(SEX = "All")) %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female")))
```

```{r}
df_hptc_tx %>%
  ggplot(aes(YEAR, SUM, group = TX, colour = TX))+
  geom_line(linewidth = 0.3)+
  facet_grid2(rows = vars(SEX),
              cols = vars(AGE))+
  theme_classic()
```
# time series

```{r}
df_hptc_loc <- df_hptc %>%
  mutate(AGE = fct_recode(AGE,
                          "0-49" = "0-39",
                          "0-49" = "40-44",
                          "0-49" = "45-49",
                          "50-59" = "50-54",
                          "50-59" = "55-59",
                          "60-69" = "60-64",
                          "60-69" = "65-69",
                          "70-79" = "70-74",
                          "70-79" = "75-79",
                          "80-" = "80-84",
                          "80-" = "85-89",
                          "80-" = "90-")) %>%
  group_by(YEAR, SEX, AGE, LOC) %>%
  summarise(SUM = sum(VALUE)) 
```


```{r}
df_hptc_loc <- df_hptc_loc  %>%
  bind_rows(df_hptc_loc %>%
              group_by(YEAR, AGE, LOC) %>%
              summarise(SUM = sum(SUM)) %>%
              mutate(SEX = "All")) %>%
  mutate(SEX = factor(SEX, levels = c("All",
                                      "Male",
                                      "Female")))
```

#

```{r}
df_hptc_comb <- df_hptc_tx %>%
  mutate(SUR = "app") %>%
  bind_rows(df_hptc_loc %>%
              rename(TX = "LOC") %>%
              mutate(SUR = "pro"))
```




```{r}
df_hptc_comb <- df_hptc_comb %>%
  mutate(ID = paste0(YEAR, "_", SEX, "_", AGE)) %>%
  left_join(df_pop_dem_sa %>% mutate(ID = paste0(YEAR, "_", SEX, "_", AGE_cat)) %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  select(!ID) %>%
  mutate(ADJ = SUM/POP * 10^2)
```

```{r}
df_hptc_comb_long <- df_hptc_comb %>%
  pivot_longer(cols = c(SUM, ADJ),
               values_to = "VALUE",
               names_to = "CAT")
```

```{r}
df_hptc_comb_long <- df_hptc_comb_long %>%
  mutate(YEAR = as.numeric(YEAR))
```


```{r}
df_hptc_comb_long <- df_hptc_comb_long %>%
  
  mutate(TX = case_when(TX == "Lap" ~ "Laparoscopic",
                        TX == "Lap (RA)" ~ "Robotic",
                        TX == "Sub_seg" ~ "Subsegment",
                        TX == "One_seg" ~ "One segment",
                        TX == "Two_seg_" ~ "Two or more\nsegments",
                        .default = TX))  %>%
  
  mutate(TX = factor(TX, levels = c("Open",
                                    "Laparoscopic",
                                    "Robotic",
                                    "Partial",
                                    "Subsegment",
                                    "One segment",
                                    "Two or more\nsegments")))
```


```{r}
df_hptc_comb_long %>%
  filter(SEX == "All") %>%
  group_by(CAT, SUR) %>%
  summarise(max = max(VALUE))
```


```{r}
y_scale_facet <- list(CAT == "SUM"  ~ scale_y_continuous(limits = c(0, 8000),
                                                         breaks = seq(0, 8000, 2000),
                                                         labels = scales::label_comma()),
                      CAT == "ADJ" ~ scale_y_continuous(limits = c(0, 80),
                                                        breaks = seq(0, 80, 20),
                                                        labels = scales::label_comma()))
```

```{r}
convert_strip <- function(x){
  if (x == "SUM"){
    return("**n**")
  }
  
  else if (x == "ADJ"){
    return("**n/10<sup>5</sup> people**")
  }
  
  else {
    return(x)
  }
}

 convert_strip <- Vectorize(convert_strip)
```


```{r}
df_y_scale <- tibble(SUR = c(rep("app", 2), rep("pro", 2)),
                     CAT = rep(c("SUM", "ADJ"),  2),
                     LAB = rep(c("**n**", "**n/10<sup>5</sup> people**"), 2 ),
                     YMAX = c(8000, 50, 5000, 30),
                     YBRK = c(2000, 10, 1000, 10)
                     )

df_y_scale 
```


```{r}
list_p1_a <- purrr::map2(df_y_scale$SUR[1:2] ,
                       df_y_scale$CAT[1:2],
                       function(x, y) {
                         
  ylab <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(LAB)
  
  ymax <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(YMAX)
  
  ybrk <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(YBRK)
                         
  df_hptc_comb_long %>%
       filter(SEX == "All") %>%
   filter(SUR == x & CAT == y) %>%
    mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
   ggplot(aes(YEAR, VALUE, group = TX, colour = TX))+
   geom_line(linewidth = 0.3)+
   scale_colour_manual(values = c("#d62728",
                                   "#1f77b4",
                                   "#bcbd22"))+
  
 # ggh4x::facetted_pos_scales(y = y_scale_facet) +
  
  scale_x_continuous(labels = c("2014", "", "2018",
                                "", "2022"),
                     limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2))+
                           
  scale_y_continuous(limits = c(0, ymax),
                     breaks = seq(0, ymax, ybrk),
                     labels = scales::label_comma())+
  
  facet_wrap2(vars(AGE) ,
               nrow = 1,
            #   scales = "free_y",
               axes = "all",
               remove_labels = "all")+
    
  guides(colour = guide_legend(override.aes = list(linewidth = 0.5) ) )+
  
  labs(y = ylab)+
                           
 # labs(tag = "A")+
  
  theme_classic()+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text = element_markdown(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 1, 0, "mm")),
        
        axis.title.x = element_blank(),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),

        legend.key.spacing.y = unit(0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        
        
        legend.position = "inside",
        legend.position.inside = c(0.01, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank(),

        legend.key.height = unit(1, "line"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 0, 1, 0, unit = "mm"),
        panel.spacing = unit(2, "mm")
        )
                       })
 
                        
```

```{r}
p1_a1 <- list_p1_a [[1]]+
  labs(tag = "A")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))


p1_a2 <- list_p1_a [[2]]+
  theme(strip.text = element_blank(),
        legend.position = "none")


p1_a1
p1_a2
```

```{r}
list_p1_b <- purrr::map2(df_y_scale$SUR[3:4] ,
                       df_y_scale$CAT[3:4],
                       function(x, y) {
                         
  ylab <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(LAB)
  
  ymax <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(YMAX)
  
  ybrk <- df_y_scale %>% filter(SUR == x & CAT == y) %>% pull(YBRK)
                         
  df_hptc_comb_long %>%
       filter(SEX == "All") %>%
   filter(SUR == x & CAT == y) %>%
        mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
   ggplot(aes(YEAR, VALUE, group = TX, colour = TX))+
   geom_line(linewidth = 0.3)+
   scale_colour_manual(values = c("#e377c2",
                                   "#2ca02c",
                                   "#ff7f0e",
                                   "#9467bd"))+
  
 # ggh4x::facetted_pos_scales(y = y_scale_facet) +
  
  scale_x_continuous(labels = c("2014", "", "2018",
                                "", "2022"),
                     limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2))+
                           
  scale_y_continuous(limits = c(0, ymax),
                     breaks = seq(0, ymax, ybrk),
                     labels = scales::label_comma())+
  
  facet_wrap2(vars(AGE) ,
               nrow = 1,
            #   scales = "free_y",
               axes = "all",
               remove_labels = "all")+
    
      guides(colour = guide_legend(override.aes = list(linewidth = 0.5),
                                 nrow = 2)) +
  
  labs(y = ylab)+
                           
 # labs(tag = "A")+
  
  theme_classic()+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text = element_markdown(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 1, 0, "mm")),
        
        axis.title.x = element_blank(),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        
        
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(0.01, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank(),
        legend.key.spacing.y = unit(0, "mm"),
        legend.key.height = unit(1, "line"),
        
        legend.key.spacing.x = unit(7.5, "mm"),
        
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 0, 1, 0, unit = "mm"),
        panel.spacing = unit(2, "mm")
        )
                       })
 
                        
```


```{r}
p1_b1 <- list_p1_b [[1]]+
  labs(tag = "B")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))


p1_b2 <- list_p1_b [[2]]+
  theme(strip.text = element_blank(),
        legend.position = "none")


p1_b1
p1_b2
```


# proportion plots


```{r}
df_hptc_comb_long %>%
    filter(SEX == "All") %>%
    filter(SUR == "pro" & CAT == "SUM") %>%
    group_by(YEAR, AGE) %>%
    mutate(ALL = sum(VALUE)) %>%
    mutate(PCT = VALUE/ALL * 100) %>% View()
```


```{r}
p1_a3 <- df_hptc_comb_long %>%
    filter(SEX == "All") %>%
    filter(SUR == "app" & CAT == "SUM") %>%
    group_by(YEAR, AGE) %>%
    mutate(ALL = sum(VALUE)) %>%
    mutate(PCT = VALUE/ALL * 100) %>%
    mutate(TX = factor(TX, levels = c("Open",
                                      "Robotic",
                                      "Laparoscopic"))) %>%
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR, PCT, fill = TX))+
    geom_col(width = 0.5, position = "stack")+
    scale_fill_manual(values = c(
                                   "#1f77b4",
                                   "#bcbd22",
                                   "#d62728"))+
  
  scale_x_continuous(labels = c("2014", "", "2018", "", "2022"),
                     breaks = seq(2014, 2022, 2))+
    scale_y_continuous(expand = c(0, 0)) +
    facet_wrap2(vars(AGE),
                nrow = 1,
                axes = "all",
                remove_labels = "all")+
     labs(
       x = "Year",
       y = "Proportion (%)")+
  theme_classic()+
   theme(
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        strip.text.y = element_blank(),
        axis.title.x =  element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x =  element_text(size = 8, colour = "black"),
        axis.text.y =  element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        
        legend.title = element_blank(),
        legend.text =  element_text(size = 8, colour = "black"),  
        legend.position = "none",
        legend.background = element_blank(),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key.spacing.y = unit(0, "mm"),
        legend.key.height = unit(1.2, "line"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 0, 0, 0, unit = "mm"),
        panel.spacing = unit(2, "mm"))

p1_a3
  
```


```{r}
p1_b3 <- df_hptc_comb_long %>%
    filter(SEX == "All") %>%
    filter(SUR == "pro" & CAT == "SUM") %>%
    group_by(YEAR, AGE) %>%
    mutate(ALL = sum(VALUE)) %>%
    mutate(PCT = VALUE/ALL * 100) %>%
    mutate(TX = factor(TX, levels = c("Two or more\nsegments",
                                        "One segment",
                                        "Subsegment",
                                        "Partial"))) %>%
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR, PCT, fill = TX))+
    geom_col(width = 0.5, position = "stack")+
    scale_fill_manual(values = c("#9467bd",
                                   "#ff7f0e",
                                  "#2ca02c",
                                 "#e377c2"))+
  
  scale_x_continuous(labels = c("2014", "", "2018", "", "2022"),
                     breaks = seq(2014, 2022, 2))+
    scale_y_continuous(expand = c(0, 0)) +
    facet_wrap2(vars(AGE),
                nrow = 1,
                axes = "all",
                remove_labels = "all")+
     labs(
       x = "Year",
       y = "Proportion (%)")+
  theme_classic()+
   theme(
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        strip.text.y = element_blank(),
        axis.title.x =  element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x =  element_text(size = 8, colour = "black"),
        axis.text.y =  element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        
        legend.title = element_blank(),
        legend.text =  element_text(size = 8, colour = "black"),  
        legend.position = "none",
        legend.background = element_blank(),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key.spacing.y = unit(0, "mm"),
        legend.key.height = unit(1.2, "line"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 0, 0, 0, unit = "mm"),
        panel.spacing = unit(2, "mm"))

p1_b3
  
```



```{r}
df_hptc_comb_long <- df_hptc_comb_long %>%
  mutate(ID = paste0(SEX, "_", AGE, "_" , TX, "_", CAT)) 
```



```{r}
# man kendall test 
# remove robotic surgery


df_hptc_comb_rkt <- df_hptc_comb_long  %>%
  
  filter(TX != "Robotic") %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ungroup() %>%
  nest(data = -ID) %>%
  mutate(
    model = purrr::map(data, ~ rkt(date = .x$YEAR,
                                 y = .x$VALUE)),
    tau = map_dbl(model, "tau"),
    p_value = map_dbl(model, "sl"),
    slope = map_dbl(model, "B")
  )

df_hptc_comb_rkt

```


```{r}
df_hptc_res <- df_hptc_comb_rkt %>%
    separate_wider_delim(cols = ID,
                       delim = "_",
                       names = c("SEX", "AGE", "TX", "CAT"))
```


```{r}
get_exp <- function(x){

  # if na return ""
  
  if(is.nan(x) | x > 0.001){
    return("")
  }
  
  else {
    
    p <- formatC(x, digits = 2, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    
    return(ex)
    }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){
  
  if (is.nan(x)){
      return("NA")
    }
  
  else if (x > 0.001) {
    p <- formatC(x, digits = 2, format = "fg", flag = "#")
    
    return(p)
  }
  
  else{
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
symbol_p <- function(x){
  if (is.na(x)){
    return(NA)
  }
  
  else if (x < 0.001){
    return("***")
  }
  
  else if (x < 0.01){
    return("**")
  }
  
  else if (x < 0.05) {
    return("*")
  }
  
  else {
   return("")
  }}

symbol_pv <- Vectorize(symbol_p)

```

```{r}
df_hptc_res %>% count(TX)

df_hptc_res %>% count(TX)
```


```{r}
df_hptc_res <- df_hptc_res %>%
  mutate(SEX = factor(SEX, levels = c("All", "Male", "Female"))) %>%
  
  mutate(TX = as.character(TX)) %>%
  mutate(TX = case_when(TX == "Lap" ~ "Laparoscopic",
                        TX == "Open" ~ "Open",
                        .default = TX)) %>%
  mutate(TX = factor(TX, levels = c("Open", "Laparoscopic",
                                    "Partial",
                                    "Subsegment",
                                    "One segment",
                                    "Two or more\nsegments"))) %>%
  
  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) %>%
  arrange(TX, AGE, SEX, CAT)

df_hptc_res
```

```{r}
df_hptc_res <- df_hptc_res %>%
  mutate(SUR = if_else(TX %in% c("Open", "Laparoscopic"), "Approach",
                       "Procedure"))
```



```{r}
df_hptc_res <- df_hptc_res %>%
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
 
  mutate(slope_label = case_when(abs(slope) < 10 ~ formatC(slope, digits = 2, format = "fg", flag = "#"),
                           .default = round(slope) %>% scales::comma())) %>%
 
  mutate(p_num = get_numv(p_value),
         p_exp = get_expv(p_value)) %>%
  
  mutate(across(c(tau_label, slope_label, p_exp), ~ str_replace_all(.x, "-", "−"))) %>%
  
  mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))}) ) %>%
  
  mutate(p_symbol = symbol_pv(p_value)) 

df_hptc_res 
```


# t1

```{r}
t1 <- df_hptc_res %>%
  filter(SUR == "Approach") %>%
  select(CAT, TX, AGE, SEX, tau_label, slope_label, p_label, p_symbol) %>%
  arrange(TX, AGE, SEX)

  
```

```{r}
t1_a <- t1 %>%
  filter(CAT == "SUM") %>%
  mutate(ID = paste(TX, "_", AGE, "_", SEX)) %>%
  select(TX, AGE, SEX, ends_with("_label"), p_symbol, ID)
  
  
t1_b <- t1 %>%
  filter(CAT == "ADJ") %>%
  mutate(ID = paste(TX, "_", AGE, "_", SEX)) %>%
  select(ends_with("_label"), p_symbol, ID)
```

```{r}
t1_ab <- t1_a %>%
  left_join(t1_b,
            by = join_by(ID),
            suffix = c("_sum", "_adj")) %>%
  select(!ID) %>%
  mutate(AGE = str_replace_all(AGE, "-", "–"))

t1_ab
```

```{r}
t1_ab <- t1_ab %>%
  rename(Approach = "TX",
         Age = "AGE",
         Sex = "SEX")
```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t1_ab) %>%
  wb_save("../table/TableS7.xlsx")
```


# t2

```{r}
t2 <- df_hptc_res %>%
  filter(SUR == "Procedure") %>%
  select(CAT, TX, AGE, SEX, tau_label, slope_label, p_label, p_symbol) %>%
  arrange(TX, AGE, SEX)

  
```

```{r}
t2_a <- t2 %>%
  filter(CAT == "SUM") %>%
  mutate(ID = paste(TX, "_", AGE, "_", SEX)) %>%
  select(TX, AGE, SEX, ends_with("_label"), p_symbol, ID)
  
  
t2_b <- t2 %>%
  filter(CAT == "ADJ") %>%
  mutate(ID = paste(TX, "_", AGE, "_", SEX)) %>%
  select(ends_with("_label"), p_symbol, ID)
```

```{r}
t2_ab <- t2_a %>%
  left_join(t2_b,
            by = join_by(ID),
            suffix = c("_sum", "_adj")) %>%
  select(!ID) %>%
  mutate(TX = str_replace_all(TX, "\n", " "))

t2_ab
```

```{r}
t2_ab <- t2_ab %>%
    mutate(TX = str_replace(TX, "Two or more", "≥ Two")) %>%
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  
  rename(Procedure = "TX",
         Age = "AGE",
         Sex = "SEX")

t2_ab 
```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t2_ab) %>%
  wb_save("../table/TableS8.xlsx")
```

# heamatp


```{r}
df_hptc_res <- df_hptc_res %>%
  mutate(TX = as.character(TX)) %>%
  mutate(TX = str_replace_all(TX, "\n", " ")) %>%
  mutate(TX = factor(TX, levels = c("Laparoscopic","Open", 
                                    
                                    "Two or more segments",
                                    "One segment",
                                    "Subsegment",
                                    "Partial")))
```

```{r}
convert_strip <- function(x){
  if (x == "SUM"){
    return("**n**")
  }
  
  else if (x == "ADJ"){
    return("**n/10<sup>5</sup> people**")
  }
  
  else {
    return(x)
  }
}

 convert_strip <- Vectorize(convert_strip)
```



```{r}
p1_c <- df_hptc_res %>%
  mutate(label = paste0(tau_label, p_symbol)) %>%
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  filter(SEX == "All") %>%
  
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%

  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) %>%
  
  ggplot(aes(AGE, TX, fill = tau))+
  geom_tile(linewidth = 0.3, colour = "black")+
  scale_fill_gradient2(low = "#74add1",
                      mid  = "white",
                      high = "#f46d43",
                      limits = c(-1, 1),
                      name = expression(tau))+
  geom_text(aes(label = label),
            size = 2.8, colour = "black")+
  facet_grid2( rows =  vars(SUR),
               cols = vars(CAT),
              switch = "y",
              scales= "free_y",
              space = "free_y",
               labeller = labeller(CAT = convert_strip))+
    scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  coord_cartesian(clip = "off")+
  labs(tag = "C",
       x= "Age",
       y = "Resection")+
    theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
          strip.placement = "outside",
          strip.background.x = element_blank(),
        strip.background.y = element_blank(),
          strip.text.x = element_markdown(size = 8, colour = "black", face = "bold",
                                          margin = margin(1, 0, 1, 0, "mm")),
          strip.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 8, colour = "black", face= "bold"),
          axis.text = element_text(size = 8, colour = "black"),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          panel.border = element_rect(colour = "black", fill=NA, linewidth=0.3),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
          legend.key.height = unit(1, "lines"),
          legend.key.width = unit(0.75, "lines"),
          plot.margin = margin(0, 0, 0, 0, "mm"),
          legend.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.spacing = unit(3, "mm"),
          panel.spacing.x = unit(3, "mm"),
          panel.spacing.y = unit(2, "mm"))
  

p1_c
```

```{r}

p1 <- p1_a1 + 
  p1_a2 +
  p1_a3 +
  
  p1_b1 + 
  p1_b2 + 
  p1_b3 +
    
  patchwork::free(p1_c, side = "lr") +
  
  plot_layout(ncol = 1,
              heights = c(rep(1, 6), 1.2))

p1
```

```{r}
ggsave("../figure/Fig4.pdf",
       p1,
       width = 175, height = 235,
       units = "mm")
```

# end
