---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(ggtext)

library(ComplexHeatmap)
library(ggh4x)

library(cowplot)
library(patchwork)
library(scales)


library(mapdata)
library(sf)
library(rnaturalearth)
library(rkt)
```


```{r}
# make df folder

dir.create("../figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../plot", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../plot/prf", showWarnings = TRUE, recursive = FALSE, mode = "0777")

dir.create("../df/rkt", showWarnings = TRUE, recursive = FALSE, mode = "0777")

```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop <- readRDS("../rds/pop/prf/df_pop_prf")
```


```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(VALUE = replace_na(VALUE, 0))
```


```{r}
df_pop <- df_pop %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", PRF))
```

```{r}
df_surg_prf %>%
   filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(CLASS_code)
```


```{r}
df_hptc_prf <- df_surg_prf %>%
   filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        ))
```


```{r}
df_hptc_prf_n  <- df_hptc_prf   %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(TX = "Resection") %>%
  ungroup()

df_hptc_prf_n
```

```{r}
df_abl_prf <- df_surg_prf %>% 
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
      mutate(TX = case_when(str_detect(PRO_name, "ラジオ") & str_detect(PRO_name, "腹腔鏡") ~ "RFA (Lap)",
                            str_detect(PRO_name, "ラジオ") & !str_detect(PRO_name, "腹腔鏡") ~ "RFA",
                            str_detect(PRO_name, "マイクロ") & str_detect(PRO_name, "腹腔鏡") ~ "MWA (Lap)",
                            str_detect(PRO_name, "マイクロ") & !str_detect(PRO_name, "腹腔鏡") ~ "MWA")) 
```

```{r}
df_abl_prf_n <- df_abl_prf %>%
  group_by(PRF, YEAR, REG, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(TX = "Ablation")
```

```{r}
df_tace_prf <- df_surg_prf %>% 
  filter((str_detect(PRO_name, "化学塞栓") )) 
```

```{r}
df_tace_prf_n <- df_tace_prf %>%
  group_by(PRF, YEAR, REG, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(TX = "TACE")
```

```{r}
df_comb_prf <- df_hptc_prf_n %>%
  bind_rows(df_abl_prf_n) %>%
  bind_rows(df_tace_prf_n) %>%
  mutate(TX = factor(TX, levels = c("Resection",
                                    "Ablation",
                                    "TACE")))
```


```{r}
df_hptc_prf %>%
  group_by(TX, LOC, YEAR, PRF) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR, SUM, group = PRF))+
  geom_line(linewidth = 0.3,
            colour= "gray")+
  facet_grid2(rows = vars(TX),
              cols = vars(LOC),
              scales = "free_y")+
  theme_classic()
  
```



```{r}
df_comb_prf  <- df_comb_prf  %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) 

```


```{r}
df_comb_prf  <- df_comb_prf  %>%
  mutate(ADJ = SUM/(POP * 1000)*10^5 )
```

# time series n 


```{r}
df_comb_prf 
```



```{r}
df_comb_prf_long <- df_comb_prf  %>%
  pivot_longer(cols = c(SUM, ADJ),
               values_to = "VALUE",
               names_to = "CAT") %>%
  mutate(CAT = factor(CAT, levels = c("SUM", "ADJ"))) 
```

```{r}
# turn NA 

df_comb_prf_long_na <- df_comb_prf_long %>%
  mutate(VALUE = case_when(YEAR == "2015" & TX == "Resection" ~ NA,
                           .default = VALUE))
```



```{r}
df_comb_prf_q <- df_comb_prf_long_na %>%
  group_by(TX, CAT, YEAR) %>%
  summarise(q_0 = quantile(VALUE, probs = 0, na.rm = TRUE),
            q_10 = quantile(VALUE, probs = 0.1, na.rm = TRUE),
            q_20 = quantile(VALUE, probs = 0.2, na.rm = TRUE),
            q_30 = quantile(VALUE, probs = 0.3, na.rm = TRUE),
            q_40 = quantile(VALUE, probs = 0.4, na.rm = TRUE),
            q_50 = quantile(VALUE, probs = 0.5, na.rm = TRUE),
            q_60 = quantile(VALUE, probs = 0.6, na.rm = TRUE),
            q_70 = quantile(VALUE, probs = 0.7, na.rm = TRUE),
            q_80 = quantile(VALUE, probs = 0.8, na.rm = TRUE),
            q_90 = quantile(VALUE, probs = 0.9, na.rm = TRUE),
            q_100 = quantile(VALUE, probs = 1.0, na.rm = TRUE))
```

```{r}
df_comb_prf_q_long <- df_comb_prf_q %>%
  pivot_longer(cols = starts_with("q_"),
               names_to = "QT",
               values_to = "VALUE")

df_comb_prf_q_long 
```


```{r}
df_comb_prf_q_long <- df_comb_prf_q_long %>%
  mutate(QT = str_remove( QT, "^q_")) %>%
  mutate(QT = as.numeric(QT)) %>%
  filter(! QT %in% c(0, 100) ) %>%
  mutate(COL = case_when(QT %in% c(10, 90) ~ 1,
                         QT %in% c(20, 80) ~ 2,
                         QT %in% c(30, 70) ~ 3,
                         QT %in% c(40, 60) ~ 4,
                         QT %in% 50 ~ 5)) %>%
  mutate(COL = factor(COL, levels = 1:5))
```




```{r}
list_scale_sum <- list(
  
  TX == "Resection" ~ scale_y_continuous(limits = c(0, 3000),
                                                        breaks = seq(0, 3000, 1000),
                                                        labels = scales::label_comma()),
  
  TX == "Ablation" ~ scale_y_continuous(limits = c(0, 4000),
                                                        breaks = seq(0, 4000, 1000),
                                                        labels = scales::label_comma()),
  
  TX == "TACE" ~ scale_y_continuous(limits = c(0, 5000),
                                                        breaks = seq(0, 5000, 1000),
                                                        labels = scales::label_comma())
)

list_scale_adj <- list(
  
  TX == "Resection" ~ scale_y_continuous(limits = c(0, 30),
                                                        breaks = seq(0, 30, 10),
                                                        labels = scales::label_comma()),
  
  TX == "Ablation" ~ scale_y_continuous(limits = c(0, 50),
                                                        breaks = seq(0, 50, 10),
                                                        labels = scales::label_comma()),
  
  TX == "TACE" ~ scale_y_continuous(limits = c(0, 80),
                                                        breaks = seq(0, 80, 20),
                                                        labels = scales::label_comma())
)



```



```{r}
convert_label <- function(x){
  if (x %in% c("SUM")){
    return("**n**")
  }
  
  else if (x %in% c("ADJ")){
    return("**n/10<sup>5</sup> people**")
  }
  
  else {
    return(NA)
  }
}

convert_label <- Vectorize(convert_label)
```

```{r}
df_comb_prf_q %>% 
    mutate(YEAR = as.numeric(YEAR)) %>% View()
```





```{r}
df_comb_prf_q %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
  filter(!(YEAR == "2015" & TX == "Resection")) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1")+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8")+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090")+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43")+
    geom_line(data = df_comb_prf_long_na  %>%
                filter(!(YEAR == "2015" & TX == "Resection")) %>%
              mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.5,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.4)+
  facet_grid2(rows = vars(CAT),
              cols = vars(TX),
              axes = "all",
              remove_labels = "x",
              scales = "free",
              switch = "y",
              labeller = labeller(CAT = convert_label ))+
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2023, 3),
                     labels = c("2014", "", "2020", ""))+
 #   ggh4x::facetted_pos_scales(y = list_scale_y)+
   labs(tag = "a",
        x = "Year")+
  theme_classic()+
   theme(plot.tag = element_text(size =12, colour = "black", face = "bold"),
         plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust = 0.5),
         strip.background = element_blank(),
         strip.text.x = element_markdown(size = 8, colour = "black", face = "bold"),
         strip.text.y.left = element_markdown(size = 8, colour = "black", face = "bold"),
         strip.placement = "outside",
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_blank(),
        axis.text.x = element_text(size = 8, colour = "black"), 
                               #  angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))
```

```{r}
tx_levels <- c("Resection", "Ablation", "TACE")

df_scale_sum <- tibble(TX = tx_levels,
                       YMAX = c(3000, 4000, 5000),
                       YBRK = c(1000, 1000, 1000))

df_scale_adj <- tibble(TX = tx_levels,
                       YMAX = c(30, 50, 80),
                       YBRK = c(10, 10, 20))


```

```{r}
list_p1_a1 <- purrr::map(tx_levels, function(tx){
  
  ymax <- df_scale_sum %>% filter(TX == tx) %>% pull(YMAX)
  
  ybrk <- df_scale_sum %>% filter(TX == tx) %>% pull(YBRK)
  
  df_comb_prf_q %>% 
    filter(CAT == "SUM") %>%
    filter(!(YEAR == "2015" & TX == "Resection")) %>%
    filter(TX == tx) %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43", alpha = 0.5)+
    geom_line(data = df_comb_prf_long  %>%
                filter(CAT == "SUM") %>%
                filter(!(YEAR == "2015" & TX == "Resection")) %>%
                filter(TX == tx) %>% 
                mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.7,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.4)+
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2),
                     labels = c("2014", "", "2018", "", "2022"))+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk),
                       labels = scales::label_comma())+
   labs(title = tx,
        x = "Year",
        y = "**n**")+
  theme_classic()+
   theme(
         plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust = 0.5,
                                  margin = margin (0, 0, 1, 0, "mm")),
         strip.background = element_blank(),
         strip.text.x = element_markdown(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"), 
                               #  angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 1, 1, 1, unit = "mm"))
} )


```


```{r}
for (i in 1:length(list_p1_a1)){
  print(list_p1_a1[[i]])
}
```

```{r}
for (i in 1:length(list_p1_a1)){
  assign( paste0("p1_a", i), list_p1_a1[[i]])
}
```

```{r}
p1_a1 <- p1_a1 +
  labs(tag = "A")+
  theme(plot.tag = element_text(size =12, colour = "black", face = "bold"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p1_a2 <- p1_a2 +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())

p1_a3 <- p1_a3 +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank())
```

```{r}
list_p1_b <- purrr::map(tx_levels, function(tx){
  
  ymax <- df_scale_adj %>% filter(TX == tx) %>% pull(YMAX)
  
  ybrk <- df_scale_adj %>% filter(TX == tx) %>% pull(YBRK)
  
  df_comb_prf_q %>% 
    filter(CAT == "ADJ") %>%
    filter(!(YEAR == "2015" & TX == "Resection")) %>%
    filter(TX == tx) %>% 
    mutate(YEAR = as.numeric(YEAR)) %>%
    ggplot(aes(YEAR))+
    geom_ribbon(aes(ymin = q_10, ymax = q_90),
              fill = "#74add1", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_20, ymax = q_80),
              fill = "#e0f3f8", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_30, ymax = q_70),
              fill = "#fee090", alpha = 0.5)+
    geom_ribbon(aes(ymin = q_40, ymax = q_60),
              fill = "#f46d43", alpha = 0.5)+
    geom_line(data = df_comb_prf_long  %>%
                filter(CAT == "ADJ") %>%
                filter(!(YEAR == "2015" & TX == "Resection")) %>%
                filter(TX == tx) %>% 
                mutate(YEAR = as.numeric(YEAR)),
            aes(YEAR, VALUE, group = PRF),
            colour = "#7f7f7f",
            alpha = 0.7,
            linewidth = 0.2,
            inherit.aes = FALSE)+
  geom_line(aes(YEAR, q_50),
            colour = "black",
            linewidth = 0.3)+
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2),
                     labels = c("2014", "", "2018", "", "2022"))+
    scale_y_continuous(limits = c(0, ymax),
                       breaks = seq(0, ymax, ybrk),
                       labels = scales::label_comma())+
   labs(
        x = "Year",
        y = "**n/10<sup>5</sup> people**")+
  theme_classic()+
   theme(
         
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y =  element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"), 
                               #  angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3),
        axis.ticks = element_line(linewidth = 0.3),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"), 
        legend.position = "none",
      #  legend.background = element_blank()
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        plot.margin = margin(1, 1, 1, 1, unit = "mm"))
} )
```

```{r}
for (i in 1:length(list_p1_b)){
  print(list_p1_b[[i]])
}
```

```{r}
for (i in 1:length(list_p1_b)){
  assign( paste0("p1_b", i), list_p1_b[[i]])
}
```

```{r}
p1_b1 <- p1_b2 +
  theme(axis.title.x = element_blank())

p1_b3 <- p1_b3 +
  theme(axis.title.x = element_blank())
```

```{r}
p1_b2 <- p1_b2 +
  theme(axis.title.y = element_blank())

p1_b3 <- p1_b3 +
  theme(axis.title.y = element_blank())
```



```{r}
p1_ab <- p1_a1 + p1_a2 + p1_a3 +
  p1_b1 + p1_b2 + p1_b3 +
  plot_layout(design = "
              ABC
              DEF")

p1_ab
```

# rkt

```{r}
df_comb_prf_long <- df_comb_prf_long %>%
  mutate(BLOCK = str_extract(iso_3166_2, "(?<=JP\\-)[:digit:]+")) %>%
  mutate(BLOCK = as.numeric(BLOCK))
```


```{r}
df_comb_prf_long <- df_comb_prf_long %>%
  mutate(ID = paste0(TX, "_", CAT))
```

# add 

```{r}
# man kendall test on raw values


df_comb_prf_rkt <- df_comb_prf_long  %>%

  mutate(YEAR = as.numeric(YEAR)) %>%
  
  mutate(VALUE = case_when(TX == "Resection" & YEAR == "2015" ~ NA,
                           .default = VALUE)) %>%
  
  ungroup() %>%
  nest(data = -ID) %>%
  mutate(
    model = purrr::map(data, ~ rkt(date = .x$YEAR,
                                 y = .x$VALUE,
                                 block = .x$BLOCK,
                                 correct = TRUE)),
    tau = map_dbl(model, "tau"),
    p_value = map_dbl(model, "sl"),
    p_value_cor = map_dbl(model, "sl.corrected"),
    slope = map_dbl(model, "B")
  )

df_comb_prf_rkt

```



```{r}
# split ID

df_comb_prf_res <- df_comb_prf_rkt %>%
  separate_wider_delim(cols = ID,
                       delim = "_",
                       names = c("TX", "CAT"))

```


```{r}
df_comb_prf_res <- df_comb_prf_res %>%
  mutate(TX = factor(TX, levels = c("Resection", "Ablation", "TACE"))) %>%
  mutate(CAT = factor(CAT, levels  = c("SUM", "ADJ")))
```


```{r}
get_exp <- function(x){

  if (x > 0.001){
    
    return("")
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% str_remove_all("(?<=\\-)0+")
    
    return(ex)
  }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){

    if (x > 0.001){
    
      p <- formatC(x, digits = 2, format = "fg", flag = "#")
      
      return(p)
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
df_comb_prf_res <- df_comb_prf_res %>%
  
   mutate(slope_label = case_when(abs(slope) < 10 ~ formatC(slope, digits = 2, format = "fg", flag= "#"),
                                 .default = round(slope) %>% as.character())) %>%
  mutate(slope_label = str_replace(slope_label, "\\.$", "\\.0$")) %>%
  
  mutate(tau_label = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
  
  mutate(p_num_label = get_numv(p_value_cor) ) %>%
  
  mutate(p_exp_label = get_expv(p_value_cor)) %>%
  
  mutate(p_symbol = case_when(p_value < 0.001 ~ "***",
                              p_value < 0.01 ~ "**",
                              p_value < 0.05 ~ "*",
                              .default = ""))  %>%
  mutate(label_beta = paste0("beta == '", slope_label, "'"),
         y_beta = 0.3) %>%
  
  mutate(label_tau = paste0("tau == '", tau_label, "'")) %>%
  
  mutate(label_p = paste0("italic(p) == '", p_num_label,
                          "'^'", p_exp_label,"'"),
         y_p = -0.3) %>%
  
  mutate(across(starts_with("label_"), ~ str_replace_all(.x, "-", "−")))

```

```{r}
df_comb_prf_res
```


```{r}
t1 <- df_comb_prf_res %>%
  
  #mutate(slope_label = str_replace_all(slope_label, "-", "−")) %>%
  #mutate(tau_label = str_replace_all(tau_label, "-", "−")) %>%
  
  #mutate(across(starts_with("label_"), ~ str_replace_all(.x, "-", "−")))
  
  mutate(p_value_label = purrr::map2(p_num_label, p_exp_label, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))
  }) )

t1
```

```{r}
t1_a <- t1 %>% filter(CAT == "SUM") %>%
  select(TX, slope_label, tau_label, p_value_label )

t1_b <- t1 %>% filter(CAT == "ADJ") %>%
  select(TX, slope_label, tau_label, p_value_label )
```

```{r}
t1_ab <- t1_a %>%
  left_join(t1_b,
            by = join_by(TX),
            suffix = c("_sum", "_adj"))

t1_ab
```
```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t1_ab) %>%
  wb_save("../table/TableS_prf_rkt.xlsx")
```


```{r}
p1_c <- df_comb_prf_res %>%
  
  mutate(CAT = case_when(CAT == "SUM" ~ "**Count (n)**",
                         CAT == "ADJ" ~ "**n per 10<sup>5</sup> people**")) %>%
  
  mutate(CAT = factor(CAT,
                      levels = c("**n per 10<sup>5</sup> people**",
                                 "**Count (n)**"))) %>%
  
  ggplot(aes(TX, CAT, fill = tau))+
  geom_tile(linewidth = 0.3, colour = "black") +
  scale_fill_gradient2(low = "#74add1",
                      mid  = "white",
                      high = "#f46d43",
                      limits = c(-1, 1),
                      name = expression(tau))+
  
  geom_text(aes(label = label_beta, nudge_y = y_beta),
            size= 2.8, colour = "black",
          #  nudge_y = y_beta,
                parse = TRUE)+
  
  geom_text(aes(label = label_tau),
            size= 2.8, colour = "black",
                parse = TRUE)+
  
  geom_text(aes(label = label_p, nudge_y = y_p),
            size= 2.8, colour = "black",
          #  nudge_y = y_p,
                parse = TRUE)+
  
  theme_classic()+
    guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  labs(tag = "B",
       x = "Treatment")+
    theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
          axis.title.x =  element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_text(size = 8, colour = "black", face = "bold"),
          axis.text.y = element_markdown(size = 8, colour = "black", face = "bold"),
          axis.line = element_blank(),
          axis.ticks = element_blank(),
          legend.title = element_text(size = 8, colour = "black", face = "bold"),
          legend.text = element_text(size = 8, colour = "black"),
          legend.key.height = unit(1, "lines"),
          legend.key.width = unit(0.75, "lines"),
          plot.margin = margin(0, 0, 0, 0, "mm"),
          legend.margin = margin(0, 0, 0, 0, "mm"))

p1_c

```

# dummy legend

```{r}
# create dummy variable
# ribbon

df_comb_prf_leg <- df_comb_prf_q_long %>%
   mutate(QTR = case_when(QT %in% c(10, 90) ~ "10–90%",
                         QT %in% c(20, 80) ~ "20–80%",
                         QT %in% c(30, 70) ~ "30–70%",
                         QT %in% c(40, 60) ~ "40–60%",
                         QT %in% 50 ~ "Median"))
```



```{r}
p1_dum <-  ggplot()+
  
  geom_line(data = df_comb_prf_leg %>%
             filter(TX == tx_levels[2]) %>%
             filter(QTR == "Median"),
           aes(YEAR, VALUE, group = QTR, colour = QTR),
          linewidth = 0.5)+
  
  scale_colour_manual(values = "black",
                      name = "Trend")+
  
  geom_col(data = df_comb_prf_leg %>%
             filter(TX == tx_levels[2]) %>%
             filter(QTR != "Median"),
           aes(YEAR, VALUE, fill = QTR),
           colour = "black",
           linewidth = 0.3)+

  scale_fill_manual(values = c("#74add1", "#e0f3f8", "#fee090", "#f46d43"),
                    name = "Percentile")+

    guides(fill = guide_legend(order = 2,
                             ncol = 1,
                             override.aes = list(colour = "black",
                                                 linewidth = 0.1,
                                                 alpha = 0.5)),
         colour = guide_legend(order = 1,
                               override.aes = list(colour = "black",
                                                 linewidth = 0.5)
                               )) +

  theme_classic()+
  theme(legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.title.position = "top",
        legend.position = "bottom",
        legend.box = "vertical",
        legend.box.just = "left",
        legend.justification = "left",
        legend.text.align = 1,
        legend.key.size = unit(5, "mm"),
        legend.spacing.y = unit(5, "mm"),
        legend.key.spacing.y = unit(0, "mm"),
      #  legend.justification = c(0, 0.5),
        legend.background = element_blank(),
        legend.margin = margin(0, 1, 0, 2, unit = "mm"),
      legend.box.margin = margin(0, 0, 0, 0, unit = "mm"))
```

```{r}
p1_leg <- p1_dum %>% get_legend() %>% wrap_plots()

p1_leg 
```

```{r}
list_plot <- list(p1_a1, p1_a2, p1_a3,
               p1_b1, p1_b2, p1_b3, 
               p1_leg)
```

```{r}
name_plot <- c("p1_a1", "p1_a2", "p1_a3",
               "p1_b1", "p1_b2", "p1_b3", 
               "p1_leg")

path_plot <- paste0("../plot/prf/", name_plot, ".RDS")
```

```{r}
for (i in 1:length(list_plot)){
  saveRDS(object = list_plot[[i]],
          file = path_plot[i])
}

```

```{r}
saveRDS(df_comb_prf_rkt, "../df/rkt/df_comb_prf_rkt.RDS")
```
