---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(fpp3)
library(ggtext)

library(broom)
library(rstatix)


library(ComplexHeatmap)
library(ggh4x)

library(factoextra)

library(patchwork)
library(scales)

# library(flextable)
#library(officer)

library(umap)
library(mapdata)
library(sf)
library(rnaturalearth)
```


```{r}
# make df folder

dir.create("../figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/cluster", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop <- readRDS("../rds/pop/prf/df_pop_prf")
```




```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") %>%
  mutate(VALUE = replace_na(VALUE, 0))
```


```{r}
df_pop <- df_pop %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", PRF))
```



```{r}
df_hptc_prf <- df_surg_prf %>%
  filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        ))
```


```{r}
df_hptc_prf  <- df_hptc_prf   %>%
  group_by(YEAR, PRF, iso_3166_2, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(TX = "Resection") %>%
  ungroup()

df_hptc_prf 
```



```{r}
df_hptc_prf  <- df_hptc_prf  %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) 

```


```{r}
df_hptc_prf  <- df_hptc_prf  %>%
  mutate(PCT = SUM/(POP*1000)*10^5 )
```


### RFA

```{r}
df_abl_prf <- df_surg_prf %>% 
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
      mutate(TX = case_when(str_detect(PRO_name, "ラジオ") & str_detect(PRO_name, "腹腔鏡") ~ "RFA (Lap)",
                            str_detect(PRO_name, "ラジオ") & !str_detect(PRO_name, "腹腔鏡") ~ "RFA",
                            str_detect(PRO_name, "マイクロ") & str_detect(PRO_name, "腹腔鏡") ~ "MWA (Lap)",
                            str_detect(PRO_name, "マイクロ") & !str_detect(PRO_name, "腹腔鏡") ~ "MWA")) 
```

```{r}
df_abl_prf <- df_abl_prf %>%
#  filter(!str_detect(TX, "LAP")) %>%
  group_by(PRF, YEAR, REG, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP*1000)*10^5 )
```


# TACE

```{r}
df_tace_prf <- df_surg_prf %>% 
  filter((str_detect(PRO_name, "化学塞栓") )) 
```

```{r}
df_tace_prf <- df_tace_prf %>%
  group_by(PRF, YEAR, REG, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) 
```


```{r}
df_tace_prf <- df_tace_prf %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP*1000)*10^5 )
```

# combine all

```{r}
df_comb_prf_all <- df_hptc_prf %>% mutate(TX = "Resection") %>%
  bind_rows(df_abl_prf  %>% mutate(TX = "Ablation")) %>%
  bind_rows(df_tace_prf %>% mutate(TX = "TACE"))
```

```{r}
df_comb_prf_all <- df_comb_prf_all %>%
  mutate(TX = factor(TX, levels = c("Resection",
                                    "Ablation",
                                    "TACE")))
```


```{r}
df_comb_prf_all %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, SUM, group = TX, colour = TX))+
  geom_line(linewidth = 0.3)+
#  geom_point(size = 1)+
  scale_colour_manual(values = c("#ff7f0e",
                                 "#2ca02c",
                                 "#9467bd"))+
  ggh4x::facet_wrap2(vars(PRF), nrow = 8, ncol = 6,
                     axes = "all",
                     remove_labels = "all",
                     scales= "free_y")+
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2))+
  scale_y_continuous(limits = c(0, NA))+
  labs(x = "Year",
       y = "**n**")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(1, 0),
        legend.justification.inside = c(1, 0),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        panel.spacing = unit(1, "mm"))

#ggsave("../figure/p_loco_prf.pdf", height = 235, width = 175, units = "mm")
```

```{r}
df_comb_prf_all %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, PCT, group = TX, colour = TX))+
  geom_line(linewidth = 0.3)+
#  geom_point(size = 1)+
  scale_colour_manual(values = c("#ff7f0e",
                                 "#2ca02c",
                                 "#9467bd"))+
  ggh4x::facet_wrap2(vars(PRF), nrow = 8, ncol = 6,
                     axes = "all",
                     remove_labels = "all")+
  scale_x_continuous(limits = c(2014, 2023),
                     breaks = seq(2014, 2022, 2))+
  scale_y_continuous(limits = c(0, NA))+
  labs(x = "Year",
       y = "**n per 10<sup>5</sup> people**")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(1, 0),
        legend.justification.inside = c(1, 0),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        panel.spacing = unit(1, "mm"))

# ggsave("../figure/p_loco_prf_pct.pdf", height = 235, width = 175, units = "mm")
```


# time series linear regression

```{r}
tsbl_comb_prf_all <- df_comb_prf_all %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = c(TX, PRF))
```

```{r}
tsbl_comb_prf_all %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR" & p.value <= 0.05 & estimate > 0) %>%
  View()
```


# combine

```{r}
df_comb_prf <- df_hptc_prf %>% filter(YEAR == "2023") %>% mutate(TX = "Resection") %>%
  bind_rows(df_abl_prf %>% filter(YEAR == "2023") %>% mutate(TX = "Ablation")) %>%
  bind_rows(df_tace_prf %>% filter(YEAR == "2023") %>% mutate(TX = "TACE"))
```


```{r}
df_comb_prf %>%
  select(PRF, TX, PCT) %>%
  pivot_wider(names_from = TX,
              values_from = PCT)
```

```{r}
df_comb_prf %>%
  select(PRF, TX, PCT) %>%
  pivot_wider(names_from = TX,
              values_from = PCT) %>%
  column_to_rownames(var = "PRF") %>%
  cor()
```


```{r}
# correlation 

pca <- df_comb_prf %>%
  select(PRF, TX, PCT) %>%
  pivot_wider(names_from = TX,
              values_from = PCT) %>%
  column_to_rownames(var = "PRF") %>%
  prcomp(scale = TRUE)

summary(pca)
```

```{r}
biplot(pca)
```

```{r}
df_comb_scale <- df_comb_prf %>%
  select(PRF, TX, PCT) %>%
  pivot_wider(names_from = TX,
              values_from = PCT) %>%
  column_to_rownames(var = "PRF") %>%
  scale()
```

```{r}
# three

nbc_method <- c("silhouette", "wss", "gap_stat")

for (i in 1:length(nbc_method)){
  
  fviz_nbclust(df_comb_scale,
             FUNcluster = cluster::pam,
             method = nbc_method[i]) %>%
    print()
}
```


```{r}
hc_comb <- hclust(dist(df_comb_scale),
                  method = "ward.D2")
```

```{r}
plot(hc_comb)
```

```{r}
ct_comb <- cutree(hc_comb, k = 3)
```

```{r}
df_hc_comb <- ct_comb %>% as.data.frame() %>%
  rename(HC = ".")

df_hc_comb 
```

```{r}
df_hc_comb %>% count(HC)
```


```{r}
df_hc_comb <- df_hc_comb %>%
  mutate(CLU = case_when(HC == 1 ~ "A",
                         HC == 2 ~ "C",
                         HC == 3 ~ "B")) %>%
  mutate(CLU = factor(CLU, levels = LETTERS[1:3]))
```



```{r}
ct_comb
```
```{r}
df_hc_comb
```

```{r}
#split <- factor(as.character(ct_comb), levels = c("1", "2", "3"))
```



```{r}
# heamtap

p1_a1 <- ComplexHeatmap::Heatmap(t(df_comb_scale) ,
                              
                              column_split = 3,
                              border_gp = grid::gpar(col = "black"),
                              
                              clustering_method_rows = "ward.D2",
                              row_names_gp = grid::gpar(fontsize = 8),
                              
                              clustering_method_columns = "ward.D2",
                            #  column_labels = column_labels,
                              column_names_gp = grid::gpar(fontsize = 8),
                              column_names_rot = 90,
                              column_dend_height = unit(5, "mm"),
                              
                              row_title_gp = gpar(fontsize = 0),
                             row_dend_width = unit(5, "mm"),
                              
                              bottom_annotation = columnAnnotation(
                                Cluster = anno_block(gp = gpar(fill = c( "#a6cee3",
                                                                         "#fb9a99",
                                                                         
                                  "#ffff99")),
                                                     labels = c("C", "A", "B"), 
                                                     labels_rot = 0,
                                                     height = unit(4, "mm"),
                                                     labels_gp = gpar(col = "black", 
                                                                      fontsize = 8))),
                              cluster_rows = TRUE,
                       
  
                              col = circlize::colorRamp2(c(-2, 0, 2), 
                                                         c("#1f77b4", "white", "#d62728")),
                              column_title_gp = gpar(fontsize = 0),

                        
                              heatmap_legend_param = list(
                                title = "Z-score",
                                title_gp = gpar(fontsize = 8, fontface = "bold"),
                                labels_gp = gpar(fontsize = 8),
                                border = "black",
                                legend_height = unit(2.5, "cm"),
                                legend_width = unit(4, "mm"))
                              )

p1_a1 <- p1_a1 %>% ggplotify::as.ggplot()

p1_a1 <- p1_a1 + labs(tag = "A")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))

p1_a1
  
```

# check distribution

```{r}
map_jp <- maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF)) %>%
  left_join(df_surg_prf %>% distinct(PRF, REG),
            by = join_by(PRF)) 
```



```{r}
p1_b1 <- map_jp %>%
  left_join(df_hc_comb %>%
              rownames_to_column(var = "PRF"),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = CLU))+
    scale_fill_manual(values = c("#fb9a99",
                                  "#ffff99",
                                 "#a6cee3"),
                      name = "Cluster")+
 scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  guides(fill =guide_legend(nrow = 1, ncol = 3, byrow=TRUE,
                             title.position = "top")) +
  guides(fill = guide_legend(override.aes = list(alpha = 1, size = 2.8, colour = "black",
                                                 linewidth = 0.1))) +
  theme_void()+
  labs(tag = "B")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
       # legend.title.position = "none",
        legend.direction = "vertical",
        legend.position.inside = c(0, 1),
       legend.justification.inside = c(0, 1),
      #  legend.justification = "left",
        legend.key.size = unit(5, "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_b1 
```


# UMAP

```{r}
set.seed(123)
umap_comb <- umap(df_comb_scale)
```

```{r}
df_umap <- umap_comb$layout %>% as.data.frame() %>%
  bind_cols(df_hc_comb) %>%
  rownames_to_column(var= "PRF")

df_umap 
```

```{r}
#set.seed(123)
#p1_b <- 
df_umap %>%
  mutate(CLU = as.factor(CLU)) %>%
  ggplot(aes(V1, V2))+
  geom_point(aes(fill = CLU, shape = CLU), colour = "black",
             size = 2)+
  scale_fill_manual(values = c("#ed97ca",
                               "#cdcc5d",
                                 "#6dccda"),
                      name = "Cluster")+
  scale_shape_manual(values = c(21, 22, 23),
                     name = "Cluster")+
  ggrepel::geom_text_repel(aes(label = PRF),
                           size = 2.6, colour = "black")+
 # scale_x_continuous(limits = c(-3, 3),
#                     breaks = seq(-3, 3, 1))+
#  scale_y_continuous(limits = c(-3, 3),
#                     breaks = seq(-3, 3, 1))+
  guides(fill = guide_legend(override.aes = list(size = 3)))+
  labs(tag = "B",
       x = "UMAP 1",
       y = "UMAP 2")+
  theme_classic()+
  theme(plot.tag= element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text =  element_text(size = 8, colour = "black"),
                axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text =  element_text(size = 8, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.position = "inside",
        legend.position.inside = c(0, 0),
        legend.justification = c(0, 0),
        legend.background = element_blank())
#p1_b
```

```{r}
set.seed(123)
df_umap %>%
  left_join(df_surg_prf %>% distinct(PRF, REG),
            by = join_by(PRF))%>%
  mutate(CLU = as.factor(CLU)) %>%
  ggplot(aes(V1, V2))+
  geom_point(aes(fill = REG, shape = CLU), colour = "black",
             size = 2)+
    scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                    guide = "none")+
  scale_shape_manual(values = c(21, 22, 23),
                     name = "Cluster")+
  ggrepel::geom_text_repel(aes(label = PRF),
                           size = 2.6, colour = "black")+
 # scale_x_continuous(limits = c(-3, 3),
#                     breaks = seq(-3, 3, 1))+
#  scale_y_continuous(limits = c(-3, 3),
#                     breaks = seq(-3, 3, 1))+
  guides(shape = guide_legend(override.aes = list(size = 3)))+
  labs(tag = "B",
       x = "UMAP 1",
       y = "UMAP 2")+
  theme_classic()+
  theme(plot.tag= element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text =  element_text(size = 8, colour = "black"),
                axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text =  element_text(size = 8, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.position = "inside",
        legend.position.inside = c(1,1),
        legend.justification = c(1, 1),
        legend.background = element_blank())

```


```{r}
 map_jp %>%
  left_join(df_hc_comb %>%
              rownames_to_column(var = "PRF"),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = CLU))+
    scale_fill_manual(values = c("#ffff99",
                                 "#fb9a99",
                                 "#a6cee3"),
                      name = "Cluster")+
 scale_x_continuous(limits = c(125, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  guides(fill =guide_legend(nrow = 1, ncol = 3, byrow=TRUE,
                             title.position = "top")) +
  guides(fill = guide_legend(override.aes = list(alpha = 1, size = 2.8, colour = "black",
                                                 linewidth = 0.3))) +
  theme_void()+
  labs(tag = "C")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "right",
       # legend.title.position = "none",
        legend.direction = "vertical",
      #  legend.position.inside = c(0, 1),
      #  legend.justification.inside = c(0, 1),
        legend.justification = "left",
        legend.key.size = unit(5, "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))
```


```{r}
tx <- c("Resection","Ablation","TACE")
```


```{r}
df_comb_prf_2023 <- df_comb_prf %>%
    select(PRF, TX, PCT) %>%
    pivot_wider(names_from = TX,
                values_from = PCT) %>%
  left_join(df_hc_comb %>% rownames_to_column(var = "PRF"),
            by = join_by(PRF))%>%
  pivot_longer(cols = c(Resection, Ablation, TACE),
               names_to = "TX",
               values_to = "PCT") %>%
  mutate(TX = factor(TX,
                     levels = c("Resection",
                                "Ablation",
                                "TACE")))
```

# facet

```{r}
#p1_c <- 
df_comb_prf_2023 %>%
  ggplot(aes(CLU, PCT,  fill = CLU))+
  geom_boxplot(alpha = 1,
                 colour = "black",
                 linewidth = 0.3,
                 median.linewidth = 1.5,
                 outlier.colour = "black",
                 outlier.shape = 1,
                 outlier.size = 1,
                 outlier.stroke = 0.3,
                 outlier.alpha = 1)+
  scale_fill_manual(values = c("#fb9a99",
                                 "#ffff99",
                                 "#a6cee3"))+
  facet_wrap2(vars(TX),
              axes = "all",
              remove_labels = "all")+
  labs(tag = "C",
       x = "Treatment",
       y = "n per 10<sup>5</sup> people")+
  theme_classic()+
  theme(plot.tag =  element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none")

#p1_c
```

```{r}
symbol_p <- function(x){
  if (x < 0.001){
    return("***")
  }
  
  else if (x < 0.01) {
    return("**")
  }
  
  else if (x < 0.05) {
    return("*")
  }
  
  else {
   return("")
  }}

symbol_pv <- Vectorize(symbol_p)

```

```{r}
#Shapiro-Wilk Normality Test

df_comb_prf_2023 %>%
  group_by(TX) %>%
  shapiro_test(PCT)
```

```{r}
df_comb_prf_2023 %>%
  group_by(TX) %>%
  shapiro_test(PCT) %>%
  mutate(statistic = formatC(statistic, digit = 2, format = "f")) %>%
  mutate(p_symbol = symbol_pv(p))  %>%
  select(TX, statistic, p, p_symbol) %>%
 # rename(Treatment = "TX") %>%
  saveRDS("../df/cluster/df_comb_shapiro.RDS")
```


```{r}
# use rstatix Kruskal-Wallis

df_comb_prf_2023 %>%
  group_by(TX) %>%
  kruskal_test(PCT ~ CLU)
```

```{r}
# use rstatix Kruskal-Wallis

df_comb_prf_2023 %>%
  group_by(TX) %>%
  kruskal_test(PCT ~ CLU) %>%
  mutate(statistic = formatC(statistic, digit = 0, format = "f")) %>%
  mutate(p_symbol = symbol_pv(p)) %>%
  select(TX, statistic, p, p_symbol) %>%
 # rename(Treatment = "TX") %>%
  saveRDS("../df/cluster/df_comb_kruskal.RDS")
```


```{r}
# use rstatix pairwise wilcoxon

df_comb_prf_2023 %>%
  group_by(TX) %>%
  dunn_test(PCT ~ CLU) 
  
```

```{r}
# use dunn

df_comb_prf_2023 %>%
  group_by(TX) %>%
  dunn_test(PCT ~ CLU,
                       p.adjust.method = "BH") %>%
  mutate(statistic = formatC(statistic, digit = 2, format = "fg", flag = "#")) %>%
  mutate(p_symbol = symbol_pv(p.adj))  %>%
  select(TX, group1, group2, statistic, p.adj, p_symbol) %>%
    rename(#Treatment = "TX",
           Cluster1 = "group1",
           Cluster2 = "group2") %>%
  saveRDS("../df/cluster/df_comb_dunn.RDS")
```

```{r}
list_p_box <- purrr::map(tx, function(x){
  df_comb_prf_2023 %>%
  filter(TX == x) %>% 
  ggplot(aes(CLU, PCT,  fill = CLU))+
  geom_boxplot(alpha = 1,
                 colour = "black",
                 linewidth = 0.3,
                 median.linewidth = 0.5,
                 outlier.colour = "black",
                 outlier.shape = 1,
                 outlier.size = 1,
                 outlier.stroke = 0.3,
                 outlier.alpha = 1)+
  scale_fill_manual(values = c( "#fb9a99",
                               "#ffff99",
                                 "#a6cee3"))+
    scale_y_continuous(
                       limits = c(0, 50),
                       breaks = seq(0, 50, 10))+
    coord_cartesian(clip = "off")+
  labs(title = x,
       x = "Cluster",
       y = "n/10<sup>5</sup> people")+
  theme_classic()+
  theme(plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust= 0.5),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
           axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
      axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0, 1.5, 0, 1.5, unit = "mm"),
        legend.position = "none")
})
```

```{r}
for (i in 1:length(list_p_box )){
  print(list_p_box [[i]])
}
```

```{r}
for (i in 1:length(list_p_box)){
  assign(paste0("p1_c", i), list_p_box[[i]])
}
```



```{r}
p1_c1 <- p1_c1+
  labs(tag = "C")+
  scale_y_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 10))+
  geom_segment(aes(x = 1.1, xend = 2.9, y = 30, yend = 30),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2, y = 30, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 1.1, xend = 1.9, y = 30-30/10, yend = 30-30/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 30-30/10, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))

p1_c1
```


```{r}
p1_c2 <- p1_c2+
   scale_y_continuous(limits = c(0, 40),
                     breaks = seq(0, 40, 10))+
  geom_segment(aes(x = 1.1, xend = 1.9, y = 40, yend = 40),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 40, label = "\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 2.1, xend = 2.9, y = 40, yend = 40),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2.5, y = 40, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+

  theme(axis.title.y = element_blank())

p1_c2
```

```{r}
p1_c3 <- p1_c3+
 
  geom_segment(aes(x = 1.1, xend = 1.9, y = 50, yend = 50),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 50, label = "\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 2.1, xend = 2.9, y = 50, yend = 50),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2.5, y = 50, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+

  theme(#axis.title.x = element_blank(),
        axis.title.y = element_blank())

p1_c3 
```

```{r}
saveRDS(p1_a1, "../plot/p1_a1.RDS")

saveRDS(p1_b1, "../plot/p1_b1.RDS")

saveRDS(p1_c1, "../plot/p1_c1.RDS")

saveRDS(p1_c2, "../plot/p1_c2.RDS")

saveRDS(p1_c3, "../plot/p1_c3.RDS")
```

```{r}
saveRDS(df_comb_prf_2023, "../df/cluster/df_comb_prf_2023.RDS")
```
