---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(openxlsx2)

library(fpp3)
library(glue)
library(ggtext)

library(ComplexHeatmap)
library(ggh4x)

library(patchwork)
library(scales)

library(factoextra)
library(cluster)

# library(flextable)
# library(officer)
library(cowplot)
library(rstatix)

library(umap)
library(mapdata)
library(sf)
library(rnaturalearth)
```


```{r}
# make df folder

dir.create("../figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_surg_prf <- readRDS("../df/prf/df_surg_prf_reg")
```

```{r}
df_pop <- readRDS("../rds/pop/prf/df_pop_prf")
```


```{r}
df_comb_prf_2023 <- readRDS("../df/cluster/df_comb_prf_2023.RDS")
```


```{r}
test_name <- list.files("../df/cluster") %>% str_remove_all("\\.RDS")

test_name <- test_name[str_detect(test_name, "kruskal|shapiro|dunn")] 

test_name
```

```{r}
test_path <- paste0("../df/cluster/", test_name, ".RDS")
```


```{r}
for (i in 1:length(test_path)){
  assign(test_name[i], readRDS(test_path[i]))
}
```


```{r}
rds_name <- list.files("../plot", pattern = "RDS") %>% str_remove("\\.RDS")

rds_name
```


```{r}
rds_path <- paste0("../plot/", rds_name, ".RDS")
```


```{r}
for (i in 1:length(rds_path)){
  assign(rds_name[i], readRDS(rds_path[i]))
}
```


```{r}
df_surg_prf <- df_surg_prf %>%
  rename(YEAR = "YEAR_str") 
```

```{r}
df_surg_prf %>%
  filter(YEAR == "2023") %>%
  filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        )) %>%
  
  View()
```


```{r}
df_surg_prf <- df_surg_prf %>%
  mutate(VALUE = replace_na(VALUE, 0))
```


```{r}
df_pop <- df_pop %>%
  rename(PRF = "PRF_en") %>%
  mutate(ID = paste0(YEAR, "_", PRF))
```



```{r}
df_hptc_prf <- df_surg_prf %>%
  filter(str_detect(CLASS_code, "^K695")) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        ))
```


```{r}
df_hptc_prf <- df_hptc_prf %>%
  mutate(LOC = factor(LOC,
                     levels = c("Partial",
                                "Sub_seg",
                                "One_seg",
                                "Two_seg_")))
```


```{r}

df_hptc_prf %>%
  group_by(TX, YEAR, PRF) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  ggplot(aes(YEAR, PCT, fill = TX)) +
  geom_col(width = 0.5)+
  facet_wrap2(vars(PRF))+
  theme_classic()

```

```{r}
df_hptc_prf %>%
  group_by(TX, YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  filter(YEAR == "2023") %>%
  ggplot(aes(PRF, PCT, fill = TX)) +
  geom_col(width = 0.5,
           position = "stack")+
  theme_classic()+
  theme(axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5))
```




```{r}
df_hptc_prf %>%
  group_by(TX, YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  filter(YEAR == "2023" & TX == "Lap") %>%
  ggplot(aes(fct_reorder(PRF,PCT), PCT, fill = REG)) +
  geom_col(width = 0.5)+
  theme_classic()+
  theme(axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5))
```


```{r}
df_hptc_prf %>%
  group_by(LOC, YEAR, PRF, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  group_by(YEAR, PRF, REG) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100) %>%
  filter(YEAR == "2023") %>%
  ggplot(aes(PRF, PCT, fill = LOC)) +
  geom_col(width = 0.5,
           position = "stack")+
  scale_fill_manual(values = c("#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#17becf"))+
  theme_classic()+
  theme(axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_hptc_prf_n <- df_hptc_prf %>%
  group_by(PRF, LOC, YEAR, REG, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) 
```


```{r}
df_hptc_prf_n <- df_hptc_prf_n %>%
  mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
  left_join(df_pop %>%
              mutate(ID = paste0(YEAR, "_", iso_3166_2)) %>%
              rename(POP = "ALL_total") %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(POP*1000)*10^5 ) %>%
  ungroup()
```


```{r}
df_hptc_prf_2023 <- df_hptc_prf_n  %>%
  filter(YEAR == "2023")
```


```{r}
df_hptc_scale <- df_hptc_prf_2023 %>%
  select(PRF, LOC, PCT) %>%
  pivot_wider(names_from = LOC,
              values_from = PCT) %>%
  column_to_rownames(var = "PRF") %>%
  scale()
```



```{r}
hc_hptc <- hclust(dist(df_hptc_scale,
                       method = "euclidean"),
                  method = "ward.D2")
```

```{r}
plot(hc_hptc)
```

```{r}
ct_hptc <- cutree(hc_hptc, k = 3)
```

```{r}
df_hc_hptc <- ct_hptc %>% as.data.frame() %>%
  rename(HC = ".")

df_hc_hptc
```

```{r}
df_hc_hptc %>% count(HC)
```

```{r}
df_hc_hptc 
```


```{r}
df_hc_hptc <- df_hc_hptc %>%
  mutate(CLU = case_when(HC == 1 ~ "D",
                         HC == 2 ~ "F",
                         HC == 3 ~ "E")) %>%
  mutate(CLU = factor(CLU, levels = LETTERS[4:6]))
```

```{r}
row_labels <- c("Partial",
                  "Subsegment",
                  "One segment",
                  "Two or more segments")
```


```{r}
# heamtap

  ComplexHeatmap::Heatmap(t(df_hptc_scale) ,
                              
                              column_split = 3,
                              border_gp = grid::gpar(col = "black"),
                              
                              clustering_method_rows = "ward.D2",
                              row_names_gp = grid::gpar(fontsize = 8),
                              
                              clustering_method_columns = "ward.D2",
                            #  column_labels = column_labels,
                              column_names_gp = grid::gpar(fontsize = 8),
                              column_names_rot = 90,
                              column_dend_height = unit(4, "mm"),
                              
                              row_title_gp = gpar(fontsize = 0),
                              row_labels = row_labels,
                              row_dend_width = unit(4, "mm"),
                            
                            
                              bottom_annotation = columnAnnotation(
                                Cluster = anno_block(gp = gpar(fill = c(
                                  "#fdbf6f",
                                  "#cab2d6",
                                "#b2df8a")),
                                                     labels = c("D", "F", "E"), 
                                                     labels_rot = 0,
                                                     height = unit(4, "mm"),
                                                     labels_gp = gpar(col = "black", 
                                                                      fontsize = 8))),
                              cluster_rows = TRUE,
  
                              col = circlize::colorRamp2(c(-2, 0, 2), 
                                                         c("#1f77b4", "white", "#d62728")),
                              column_title_gp = gpar(fontsize = 0),
                              
                              heatmap_legend_param = list(
                                title = "Z score",
                                title_gp = gpar(fontsize = 8, fontface = "bold"),
                                labels_gp = gpar(fontsize = 8),
                                border = "black",
                                legend_height = unit(3, "cm"))
                              )

```

```{r}
# heamtap

p1_a2 <- ComplexHeatmap::Heatmap(t(df_hptc_scale) ,
                              
                              column_split = 3,
                              border_gp = grid::gpar(col = "black"),
                              
                              clustering_method_rows = "ward.D2",
                              row_names_gp = grid::gpar(fontsize = 8),
                              
                              clustering_method_columns = "ward.D2",
                            #  column_labels = column_labels,
                              column_names_gp = grid::gpar(fontsize = 8),
                              column_names_rot = 90,
                              column_dend_height = unit(5, "mm"),
                              
                              row_title_gp = gpar(fontsize = 0),
                              row_labels = row_labels,
                              row_dend_width = unit(5, "mm"),
                            
                            
                              bottom_annotation = columnAnnotation(
                                Cluster = anno_block(gp = gpar(fill = c(
                                  "#fdbf6f",
                                  "#cab2d6",
                                "#b2df8a")),
                                                     labels = c("D", "F", "E"), 
                                                     labels_rot = 0,
                                                     height = unit(4, "mm"),
                                                     labels_gp = gpar(col = "black", 
                                                                      fontsize = 8))),
                              cluster_rows = TRUE,
  
                              col = circlize::colorRamp2(c(-2, 0, 2), 
                                                         c("#1f77b4", "white", "#d62728")),
                              column_title_gp = gpar(fontsize = 0),
                              
                              show_heatmap_legend = FALSE
                              )

p1_a2 <- p1_a2 %>% ggplotify::as.ggplot()

p1_a2 <- p1_a2 +
  #labs(tag = "B")+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))

p1_a2
  
```

# check distribution

```{r}
map_jp <- maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF)) %>%
  left_join(df_surg_prf %>% distinct(PRF, REG),
            by = join_by(PRF)) 
```



```{r}
p1_b2 <- map_jp %>%
  left_join(df_hc_hptc %>%
              rownames_to_column(var = "PRF"),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = CLU))+
    scale_fill_manual(values = c( "#fdbf6f",
                                "#b2df8a",
                                 "#cab2d6"),
                      name = "Cluster")+
 scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  guides(fill =guide_legend(nrow = 1, ncol = 3, byrow=TRUE,
                             title.position = "top")) +
  guides(fill = guide_legend(override.aes = list(alpha = 1, size = 2.8, colour = "black",
                                                 linewidth = 0.1))) +
  theme_void()+
  theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
       # legend.title.position = "none",
        legend.direction = "vertical",
       legend.justification = "inside",
       legend.position.inside = c(0, 1),
        legend.justification.inside = c(0, 1),
        legend.key.size = unit(5, "mm"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_b2
```

```{r}
df_hptc_prf_2023 <- df_hptc_prf_2023  %>%
  left_join(df_hc_hptc %>% rownames_to_column(var = "PRF"),
            by = join_by(PRF))
```



```{r}
df_hptc_prf_2023  %>%
  ggplot(aes(LOC, PCT, fill = LOC))+
  geom_boxplot()+
  facet_wrap2(vars(CLU))+
  theme_classic()
```

```{r}
df_hptc_prf_2023  %>%
  ggplot(aes(CLU, PCT, fill = LOC))+
  geom_boxplot()+
  facet_wrap2(vars(LOC), nrow = 1)+
  scale_y_continuous(limits =c(0, 15),
                     breaks = seq(0, 15, 5))+
  theme_classic()
```

```{r}
df_hptc_prf_2023 
```



```{r}
df_hptc_prf_2023  %>%
  nest(data = -LOC) %>%
  mutate(
    test = purrr::map(data, ~  pairwise.wilcox.test(.x$PCT, .x$CLU,
                                             p.adjust.method = "bonferroni",
                                             data = .)),
    tidied = purrr::map(test, broom::tidy)
  ) %>%
  unnest(tidied) %>%
  mutate(sig = case_when(p.value < 0.05 ~ 1,
                         .default = 0)) %>% View()
```

```{r}
df_hptc_prf_2023 %>% count(LOC)
```


```{r}
df_hptc_prf_2023 <- df_hptc_prf_2023 %>%
  mutate(LABEL = case_when(LOC == "Sub_seg" ~ "Subsegment",
                           LOC == "One_seg" ~ "One segment",
                           LOC == "Two_seg_" ~ "Two or more segments",
                           .default = LOC))
```

```{r}
levels_label <- df_hptc_prf_2023 %>% distinct(LOC, .keep_all = TRUE) %>%
  arrange(LOC) %>% pull(LABEL)

df_hptc_prf_2023 <- df_hptc_prf_2023 %>%
  mutate(LABEL = factor(LABEL, levels = levels_label))
```

```{r}
symbol_p <- function(x){
  if (x < 0.001){
    return("***")
  }
  
  else if (x < 0.01) {
    return("**")
  }
  
  else if (x < 0.05) {
    return("*")
  }
  
  else {
   return("")
  }}

symbol_pv <- Vectorize(symbol_p)

```


```{r}
#Shapiro-Wilk Normality Test

df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  shapiro_test(PCT) 
```


```{r}
#Shapiro-Wilk Normality Test

df_hptc_shapiro <- df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  shapiro_test(PCT) %>%
  mutate(statistic = formatC(statistic, digit = 2, format = "f")) %>%
  mutate(p_symbol = symbol_pv(p))  %>%
  select(LABEL, statistic, p, p_symbol) %>%
  rename(TX = "LABEL") 
```

```{r}
df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  kruskal_test(PCT ~ CLU)
```


```{r}
#  kruskal_test

df_hptc_kruskal <- df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  kruskal_test(PCT ~ CLU) %>%
  mutate(statistic = formatC(statistic, digit = 0, format = "f")) %>%
  mutate(p_symbol = symbol_pv(p)) %>%
  select(LABEL, statistic, p, p_symbol) %>%
  rename(TX = "LABEL") 

df_hptc_kruskal 
```

```{r}
df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  dunn_test(PCT ~ CLU) %>%
  mutate(p_symbol = symbol_pv(p.adj)) 
```

```{r}
df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  dunn_test(PCT ~ CLU,
                       p.adjust.method = "BH") 
```


```{r}
df_hptc_dunn <- df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  dunn_test(PCT ~ CLU,
                       p.adjust.method = "BH") %>%
  
  mutate(statistic = formatC(statistic, digit = 2, format = "fg",
                             flag = "#")) %>%
  mutate(statistic = str_replace(statistic, "\\.$", "\\.0")) %>%
  
  mutate(p_symbol = symbol_pv(p.adj))  %>%
  select(LABEL, group1, group2, statistic, p.adj, p_symbol) %>%
    rename(TX = "LABEL",
           Cluster1 = "group1",
           Cluster2 = "group2") 

df_hptc_dunn
```


```{r}
get_exp <- function(x){

  # if na return ""
  
  if(is.nan(x) | x > 0.001){
    return("")
  }
  
  else {
    
    p <- formatC(x, digits = 2, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>% 
      str_remove_all("(?<=\\-)0+") %>%
      str_replace("-", "−")
    
    
    return(ex)
    }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){
  
  if (is.nan(x)){
      return("NA")
    }
  
  else if (x > 0.001) {
    p <- formatC(x, digits = 2, format = "fg", flag = "#")
    
    return(p)
  }
  
  else{
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```



```{r}
df_shapiro <- df_comb_shapiro %>%
  mutate(Category = "Treatment") %>%
  bind_rows(df_hptc_shapiro %>%
              mutate(Category  = "Liver resection")) %>%
  relocate(Category, .before = "TX") %>%
  rename(W_statistic = "statistic")

df_shapiro

```



```{r}
t1 <-  df_shapiro %>%
  mutate(p_num = get_numv(p),
         p_exp = get_expv(p)) %>%
  
  mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))}) ) 

t1
```

```{r}
t1 <- t1 %>%
  select(Category, TX, W_statistic, p_label, p_symbol) %>%
  rename(Procedure = "TX",
         p_value = "p_label")

```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t1) %>%
  wb_save("../table/TableS10.xlsx")
```


```{r}
df_kruskal <- df_comb_kruskal %>%
  mutate(Category = "Treatment") %>%
  bind_rows(df_hptc_kruskal %>%
              mutate(Category  = "Liver resection")) %>%
  relocate(Category, .before = "TX") %>%
  rename(H_statistic = "statistic")

df_kruskal
```

```{r}
t2 <-  df_kruskal %>%
  mutate(p_num = get_numv(p),
         p_exp = get_expv(p)) %>%
  
  mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))}) ) 

t2
```

```{r}
t2 <- t2 %>%
  select(Category, TX, H_statistic, p_label, p_symbol) %>%
  rename(
         Procedure = "TX",
         p_value = "p_label")

```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t2) %>%
  wb_save("../table/TableS11.xlsx")
```



```{r}
df_dunn <- df_comb_dunn %>%
  mutate(Category = "Treatment") %>%
  bind_rows(df_hptc_dunn %>%
              mutate(Category  = "Liver resection")) %>%
  relocate(Category, .before = "TX") %>%
  rename(Z_statistic = "statistic")

df_dunn

```

```{r}
t3 <-  df_dunn %>%
  mutate(p_num = get_numv(p.adj),
         p_exp = get_expv(p.adj)) %>%
  
  mutate(Z_statistic = str_replace_all(Z_statistic, "-", "−")) %>%
  
  mutate(p_label = purrr::map2(p_num, p_exp, function(x, y){
    c(fmt_txt(x), fmt_txt(y, vert_align = "superscript"))}) ) 

t3
```

```{r}
t3 <- t3 %>%
  select(Category, TX, Cluster1, Cluster2, Z_statistic, p_label, p_symbol) %>%
  rename(
         Procedure = "TX",
         p_value = "p_label")

```


```{r}
wb_workbook() %>%
  wb_add_worksheet("Sheet1") %>%
  wb_add_data(x = t3) %>%
  wb_save("../table/TableS12.xlsx")
```



```{r}
df_hptc_prf_2023 %>%
  group_by(LABEL) %>%
  summarise(max = max(PCT))
```

```{r}
list_p_box <- purrr::map(levels_label, function(x){
  df_hptc_prf_2023 %>%
  filter(LABEL == x) %>% 
  ggplot(aes(CLU, PCT,  fill = CLU))+
  geom_boxplot(alpha = 1,
                 colour = "black",
                 linewidth = 0.3,
                 median.linewidth = 0.5,
                 outlier.colour = "black",
                 outlier.shape = 1,
                 outlier.size = 1,
                 outlier.stroke = 0.3,
                 outlier.alpha = 1)+
    scale_fill_manual(values = c(
                                 "#fdbf6f",
                                "#b2df8a",
                                 "#cab2d6"))+
    scale_y_continuous(
                       limits = c(0, 15),
                       breaks = seq(0, 15, 5))+
    coord_cartesian(clip = "off") +
  labs(title = x,
       x = "Cluster",
       y = "n/10<sup>5</sup> people")+
  theme_classic()+
  theme(plot.title = element_text(size = 8, colour = "black", face = "bold",
                                  hjust= 0.5),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
           axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
      axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0, 1.5, 0, 1.5, unit = "mm"),
        legend.position = "none")
})
```

```{r}
for (i in 1:length(list_p_box )){
  print(list_p_box [[i]])
}
```

```{r}
for (i in 1:length(list_p_box)){
  assign(paste0("p1_d", i), list_p_box[[i]])
}
```


```{r}
p1_d1 <- p1_d1 + 
  labs(tag = "D")+
  geom_segment(aes(x = 1.1, xend = 2.9, y = 15, yend = 15),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2, y = 15, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
   geom_segment(aes(x = 1.1, xend = 1.9, y = 15 - 15/10, yend = 15 - 15/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 15 - 15/10, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"))

p1_d1 
```

```{r}
p1_d2 <- p1_d2 + 
  
  scale_y_continuous(limits = c(0, 6),
                     breaks = seq(0,6, 2)) +
  
  geom_segment(aes(x = 1.1, xend = 2.9, y = 6, yend = 6),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2, y = 6, label = "\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 1.1, xend = 1.9, y = 6 - 6/10, yend = 6 - 6/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 6 - 6/10, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 2.1, xend = 2.9, y = 6 - 6/10, yend = 6 - 6/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2.5, y = 6 - 6/10, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  theme(axis.title.y = element_blank())

p1_d2 
```

```{r}
p1_d3 <- p1_d3 + 
  
  scale_y_continuous(limits = c(0, 4),
                     breaks = seq(0, 4, 1)) +
  
  geom_segment(aes(x = 1.1, xend = 2.9, y = 4, yend = 4),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2, y = 4, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  geom_segment(aes(x = 1.1, xend = 1.9, y = 4 - 4/10, yend = 4 - 4/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 4 - 4/10, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  theme(axis.title.y = element_blank())

p1_d3 
```



```{r}
p1_d4 <- p1_d4 + 
  
    
  scale_y_continuous(limits = c(0, 4),
                     breaks = seq(0, 4, 1)) +
  
   geom_segment(aes(x = 1.1, xend = 2.9, y = 4, yend = 4),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 2, y = 4, label = "\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
   geom_segment(aes(x = 1.1, xend = 1.9, y = 4 - 4/10, yend = 4 - 4/10),
               linewidth = 0.3, colour = "black")+
  geom_richtext(data = tibble(x = 1.5, y = 4 - 4/10, label = "\\*\\*\\*"),
                aes(x = x, y = y, label = label),
                size = 2.8, colour = "black",
                vjust = 0.5,
                label.padding = unit(c(0, 0, 0, 0), "mm"),
                label.margin = unit(c(0, 0, 0, 0), "mm"),
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  
  theme(axis.title.y = element_blank())

p1_d4 
```

```{r}
# p1_d <- p1_e1 + p1_e2 + p1_e3 + p1_e4 +
#  plot_layout(nrow = 1, ncol = 4,
#              axis_titles = "collect_x")

#p1_e 
```


```{r}
#p1_e <- p1_e1 + p1_e2 + p1_e3 +
##  plot_layout(nrow = 1, ncol = 3,
#              axis_titles = "collect_x")

#p1_e
```


```{r}
df_tile <- df_comb_prf_2023 %>%
  distinct(PRF, CLU) %>%
  rename(CLU_tx = "CLU") %>%
  left_join(df_hptc_prf_2023 %>%
              distinct(PRF, CLU) %>%
              rename(CLU_hp = "CLU"),
            by= join_by(PRF))
```

```{r}
df_tile %>%
  count(CLU_tx, CLU_hp)
```


```{r}
df_tile %>%
  count(CLU_tx, CLU_hp) %>%
  tidyr::complete(CLU_tx, CLU_hp, fill = list(n = 0)) %>%
  mutate(label = n) %>%
  mutate(label = case_when(label == 0 ~ NA,
                           .default = as.character(label))) %>%
  mutate(pct = round(n/47*100)) %>%
  mutate(label = case_when(!is.na(label) ~ paste0(label, "\n(", pct, "%)"),
                           .default = NA))
```


```{r}
p1_b3 <- df_tile %>%
  count(CLU_tx, CLU_hp) %>%
  tidyr::complete(CLU_tx, CLU_hp, fill = list(n = 0)) %>%
  mutate(label = n) %>%
  mutate(label = case_when(label == 0 ~ NA,
                           .default = as.character(label))) %>%
  mutate(pct = round(n/47*100)) %>%
  mutate(label = case_when(!is.na(label) ~ paste0(label, "\n(", pct, "%)"),
                           .default = NA)) %>%
  ggplot(aes(CLU_tx, CLU_hp))+
  geom_tile(aes(fill = n),
            colour = "black",
            linewidth = 0.3)+
  scale_fill_gradient(low = "white", high = "#E64626",
                      limits = c(0, 20),
                      breaks = seq(0, 20, 5),
                      name = "Prefecture\n(n)") +
  geom_text(aes(label = label),
            size = 2.8, colour = "black") +
    guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2,
                                title.position = "left")) +
  labs(#tag = "E",
       x = "Cluster",
       y = "Cluster")+
  scale_x_discrete(expand = c(0, 0))+
  scale_y_discrete(expand = c(0, 0))+
  coord_cartesian(clip = "off")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.3),
        legend.position = "bottom",
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
       legend.title = element_text(size = 8, colour = "black", face = "bold",
                                   vjust = 1,
                                   hjust = 0.5),
       legend.key.height = unit(1, units = "line"),
       legend.key.width = unit(0.75, units = "line"),
       legend.text = element_text(size = 8, colour = "black"),
       legend.margin = margin(0, 0, 0, 0, unit = "mm")
        )

p1_b3
```

```{r}

p1_b3_leg <- p1_b3 %>% get_legend()

p1_b3_leg <- wrap_elements(p1_b3_leg)
  
p1_b3_no_leg <- p1_b3 + theme(legend.position = "none")
```

```{r}
df_comb_prf_2023 %>%
  distinct(PRF, CLU) %>%
  rename(CLU_tx = "CLU") 
```

```{r}
p1_a1 <- p1_a1 + coord_cartesian(clip = "off")
```


```{r}
p1 <- patchwork::free(p1_a1) + 
  patchwork::free(p1_a2) + 
  patchwork::free(p1_b1, side = "tb") + patchwork::free(p1_b2, side = "tb")  + patchwork::free(p1_b3_no_leg, side = "lr") + 
  patchwork::free(p1_b3_leg, side = "lr") +
  p1_c1 + p1_c2 + p1_c3 +
  p1_d1 + p1_d2 + p1_d3 + p1_d4 +
  plot_layout(design = "
              AAAAAAAA
              AAAAAAAA
              AAAAAAAA
              AAAAAAAA
              AAAAAAAA
              AAAAAAAA
              BBBBBBBB
              BBBBBBBB
              BBBBBBBB
              BBBBBBBB
              BBBBBBBB
              BBBBBBBB
              BBBBBBBB
              CCCDDDEE
              CCCDDDEE
              CCCDDDEE
              CCCDDDEE
              CCCDDDFF
              CCCDDDFF
              GGHHII##
              GGHHII##
              GGHHII##
              JJKKLLMM
              JJKKLLMM
              JJKKLLMM")

p1
```

```{r}
ggsave("../figure/Fig7.pdf", p1,
       width = 175, height = 235, units = "mm")
```

```{r}
saveRDS(df_hptc_prf_2023, "../df/cluster/df_hptc_prf_2023.RDS")
```

# end of run