---
title: "Liver cancer"
output: html_document
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(readxl)
library(openxlsx)

library(fpp3)
library(anomalize)

library(ggtext)
library(cowplot)
library(patchwork)

library(pals)

library(scales)
library(stringi)
library(stringr)
```


```{r}
# make df folder

dir.create("../df/stl", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


# covid

```{r}
rds_covid <- list.files("../rds/covid")
```

```{r}
path_covid <- paste0("../rds/covid/", rds_covid)
```


```{r}
list_covid <- purrr::map(path_covid, readRDS)
```


```{r}
for (i in 1:length(list_covid )){
  assign(rds_covid[i], list_covid[[i]])
}
```

```{r}
colnames(df_inpt)[2] <- "ALL" 
```

```{r}
df_daily %>% filter(ALL == max(ALL))
```


```{r}
df_soe1 <- tibble(xmin = as_date("2020-04-07"),
                 xmax = as_date("2020-05-25"),
                 ymin = -Inf,
                 ymax = Inf)
```

```{r}
df_soe2 <- tibble(xmin = as_date("2021-01-08"),
                 xmax = as_date("2021-03-21"),
                 ymin = -Inf,
                 ymax = Inf)
```

```{r}
df_soe3 <- tibble(xmin = as_date("2021-04-25"),
                 xmax = as_date("2021-09-30"),
                 ymin = -Inf,
                 ymax = Inf)
```

```{r}
# monthly

p1_a1 <- df_daily %>%
  mutate(ALL = ALL/10^3) %>%
  ggplot(aes(YMD, ALL))+
      geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(linewidth = 0.3, colour = "#848482")+
  scale_x_date(date_labels = "%Y",
                limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
    scale_y_continuous(limits = c(0, 3*10^2),
                       breaks = seq(0, 3*10^2, 1*10^2),
                       labels = scales::label_comma())+
   theme_classic()+
  labs(tag = "A",
       title = "New cases",
       x = "Year",
       y = "**Count (×10<sup>3</sup>)**")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5,
                                  margin = margin(0, 0, 1, 0, "mm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title.y = element_markdown(size = 8, colour = "black", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_a1 

```


```{r}
p1_a2 <- df_inpt %>%
  mutate(ALL = ALL/10^6) %>%
  ggplot(aes(YMD, ALL))+
       geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(linewidth = 0.3, colour = "#848482")+
   theme_classic()+
  labs(#tag = "a",
    title = "Cases under care",
       x = "Year",
       y = "**Count (×10<sup>6</sup>)**")+
    scale_x_date(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 2),
                     breaks = seq(0, 2, 0.5),
                     labels = scales::label_comma())+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5,
                                  margin = margin(0, 0, 1, 0, "mm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title.y = element_markdown(size = 8, colour = "black", hjust = 0.5),
        axis.text = element_text(size = 8, colour = "black", hjust = 0.5),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_a2
```


# monthly endoscopy

```{r}
df_test_mon_reg <-  readRDS("../df/mon/df_mon_test_reg")

df_test_mon_add <-  readRDS("../df/mon/df_mon_test_add")
```

```{r}
df_surg_mon_reg <-  readRDS("../df/mon/df_mon_surg_reg")

df_surg_mon_add <-  readRDS("../df/mon/df_mon_surg_add")
```

```{r}
df_surg_mon_reg %>% 
      filter(str_detect(ORGAN, "腹部") & 
                    str_detect(PRO_name, "肝切除術")) %>%
  count(CLASS_code, CLASS_name)
```

```{r}
df_hptc <- df_surg_mon_reg  %>% 
  filter(str_detect(CLASS_code, "^K695") ) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                         str_detect(PRO_name, "外側区域|１区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        )) %>%
  mutate(TX = factor(TX, levels = c("Open",
                                    "Lap",
                                    "Lap (RA)")))


df_hptc 
```

```{r}
df_hptc %>% filter(YEAR_str == "2022") %>% View()
```

```{r}
ts_hptc_tx <- df_hptc %>%
    filter(TX != "Lap (RA)") %>%
 group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) %>%
  bind_rows(df_hptc %>%
              group_by(YMD) %>%
              summarise(SUM = sum(VALUE)) %>%
              mutate(TX = "Total")) %>%
  mutate(YM = yearmonth(YMD)) %>%
  mutate(TX = factor(TX, levels = c("Total",
                                    "Open",
                                    "Lap"))) 

ts_hptc_tx 
```

```{r}
stl_hptc_tx <- ts_hptc_tx %>%
  group_by(TX) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_hptc_tx
```

```{r}
stl_hptc_tx  <- stl_hptc_tx   %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 
```

```{r}
stl_hptc_tx  %>%
  count(anomaly)
```


```{r}
stl_hptc_tx   <- stl_hptc_tx    %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
  mutate(y_point = case_when(anomaly == "Yes" ~ observed,
                         .default = NA)) %>%
  
  mutate(y = case_when(anomaly == "Yes" & remainder >0 & TX == "Total" ~ 1800,
                       anomaly == "Yes" & remainder < 0 & TX == "Total" ~ 1800,
                       anomaly == "Yes" & remainder >0 & TX == "Lap" ~ 500,
                       anomaly == "Yes" & remainder < 0 & TX == "Lap" ~ 500,
                       
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
p1_g1 <- stl_hptc_tx   %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +

    geom_point(aes(YMD, y_point, colour = TX),
             alpha = 0.8, stroke = 0.75,
             shape = 21, fill = NA,
             show.legend = FALSE)+
  scale_colour_manual(values = c("#ff7f0e",
                                 "#1f77b4",
                                 "#d62728"),
                      name = "",
                      labels = c("Total",
                                 "Open",
                                 "Laparoscopic"))+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 2000),
                     breaks = seq(0, 2000, 500),
                     labels = label_comma())+
    guides(colour = guide_legend( 
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "G",
      # title = "Resection",
       x = "Year",
       y = "**Resection (n)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         # plot.title = element_text(size = 8, colour = "black", face = "bold",hjust = 0.5,
        #                            margin = margin(1, 0, 0, 1, unit = "mm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(1, 0, 0, 0, unit = "mm")),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        legend.position = "bottom",
        legend.justification = c(0, 0.5),
        legend.position.inside = c(0, 0.5),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
      legend.key.height = unit(5, "mm"),
      legend.spacing.y = unit(0, "mm"),
      legend.box.spacing = unit(0, "mm"))

p1_g1
```

```{r}
df_hptc_robotic <- df_hptc %>%
  filter(TX == "Lap (RA)") %>%
  group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE))

df_hptc_robotic
```


```{r}
df_hptc_robotic %>%
  mutate(YEAR = year(YMD)) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(SUM))
```


```{r}
df_hptc_loc <- df_surg_mon_reg  %>% filter(str_detect(CLASS_code, "^K695") ) %>%
  mutate(LOC = case_when(str_detect(PRO_name, "部分切除")  ~  "Partial", 
                         str_detect(PRO_name, "亜区域切除")  ~  "Sub_seg",
                      #   str_detect(PRO_name, "（外側区域切除）") ~ "Lateral_seg",
                         str_detect(PRO_name, "１区域切除|外側区域切除")  ~  "One_seg",
                         str_detect(PRO_name, "２区域切除|３区域切除")  ~  "Two_seg_",
                        .default = NA
                        )) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "腹腔鏡") & str_detect(PRO_name, "手術用支援機器") ~  "Lap (RA)",
                        str_detect(PRO_name, "腹腔鏡") & !str_detect(PRO_name, "手術用支援機器") ~ "Lap",
                        .default = "Open"
                        ))
```

```{r}
ts_hptc_loc <- df_hptc_loc %>%
  group_by(YMD, LOC) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(YM = yearmonth(YMD)) %>%
  mutate(LOC = factor(LOC,
                      levels = c("Partial",
                                 "Sub_seg",
                                 "One_seg",
                                 "Two_seg_")
                      )) 
```

```{r}
stl_hptc_loc <- ts_hptc_loc %>%
  group_by(LOC) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_hptc_loc
```

```{r}
stl_hptc_loc  <- stl_hptc_loc   %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 
```

```{r}
stl_hptc_loc  %>%
  count(anomaly)
```


```{r}
stl_hptc_loc   <- stl_hptc_loc   %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
  mutate(y_point = case_when(anomaly == "Yes" ~ observed,
                         .default = NA)) %>%
  mutate(y = case_when(anomaly == "Yes" & LOC == "One_seg"  ~ 500,
                       anomaly == "Yes" & LOC == "Two_seg_"  ~ 400,
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                         .default = NA))
```

```{r}
p1_g2 <- stl_hptc_loc   %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = LOC),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = LOC),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = LOC, colour = LOC),
            alpha = 0.8,
            linewidth = 0.5) +
     geom_point(aes(YMD, y_point, colour = LOC),
                fill = NA,
             alpha = 0.8, size = 1,
             shape = 21, stroke = 0.75,
             show.legend = FALSE)+
  scale_colour_manual(values = c("#e377c2",
                                  "#2ca02c",
                                 "#ff7f0e",
                                   "#9467bd"),
                      name= "Resection",
                      labels = c("Partial",
                                 "Sub-\nsegment",
                                 "One\nsegment",
                                 "Two or more\nsegments"))+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 1000),
                     breaks = seq(0, 1000, 250),
                     labels = label_comma())+
    guides(colour = guide_legend(nrow = 1,
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(#tag = "G",
       x = "Year",
       y = "**Resection (n)**")+
  theme_classic()+
    theme(#plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "bottom",
        legend.justification = c(1, 0.5),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key.height = unit(5, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_g2
```

# advanced based on year

```{r}
df_abl <- df_surg_mon_reg  %>%
  filter( (str_detect(PRO_name, "肝悪性腫瘍ラジオ波焼灼療法") |
             str_detect(PRO_name, "肝悪性腫瘍マイクロ波凝固法"))) %>%
  
  mutate(TX = case_when(str_detect(PRO_name, "ラジオ波")  ~  "RFA",
                        str_detect(PRO_name, "マイクロ波")  ~ "MWA"
                        ))


df_abl
```

```{r}
ts_abl <- df_abl %>%
 group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) %>%
  bind_rows(df_abl %>%
              group_by(YMD) %>%
              summarise(SUM = sum(VALUE)) %>%
              mutate(TX = "Total")) %>%
  mutate(YM = yearmonth(YMD)) %>%
  mutate(TX = factor(TX,
                     levels = c("Total",
                                "RFA",
                                "MWA"))) 
ts_abl
```

```{r}
stl_abl <- ts_abl %>%
  group_by(TX) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_abl 
```


```{r}
stl_abl  <- stl_abl   %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 

```

```{r}
stl_abl %>%
  ungroup() %>%
  summarise(MAX_obs = max(observed),
            MAX_adj = max(season_adj))
```


```{r}
stl_abl  <- stl_abl   %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
  mutate(y_point = case_when(anomaly == "Yes" ~ observed,
                         .default = NA)) %>%
  
  mutate(y = case_when(anomaly == "Yes" &  TX == "Total" ~ 1700,
                       
                       anomaly == "Yes" & TX == "RFA" ~ 800,
                       anomaly == "Yes" &  TX == "MWA" ~ 400,
                       
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
p1_e <- stl_abl   %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
  geom_point(aes(YMD, y_point, colour = TX),
             size = 1, alpha = 0.8, 
             shape = 21, stroke = 0.75, 
             show.legend = FALSE)+
  scale_colour_manual(values = c("#2ca02c",
                                 "#e377c2",
                                 "#17becf"),
                      name = "")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 1600),
                     breaks = seq(0, 1600, 400),
                     labels = scales::label_comma())+
    guides(colour = guide_legend(nrow = 3,
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "E",
       x = "Year",
       y = "**Ablation (n)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        legend.position = "inside",
        legend.justification.inside = c(0, 0.5),
        legend.position.inside = c(0.025, 6.5/16),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.key.height = unit(5, "mm"),
        legend.box.spacing = unit(0, "mm"))

p1_e
```


```{r}
df_tace <- df_surg_mon_reg  %>%
  filter( (str_detect(PRO_name, "化学塞栓")))
  
df_tace
```

```{r}
ts_tace <- df_tace %>%
  mutate(TX = "TACE") %>%
  group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) 
```


```{r}
stl_tace <- ts_tace %>%
  group_by(TX) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_tace
```


```{r}
stl_tace <- stl_tace  %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 

```

```{r}
stl_tace <- stl_tace  %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
  mutate(y_point = case_when(anomaly == "Yes" ~ observed,
                         .default = NA)) %>%
  
  mutate(y = case_when(anomaly == "Yes" & remainder > 0 ~ 2800,
                       anomaly == "Yes" & remainder < 0 ~ 2800, 
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
p1_f <- stl_tace   %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
  geom_point(aes(YMD, y_point, colour = TX),
             fill = NA,
             alpha = 0.8, size = 1,
            shape = 21, stroke = 0.75,
             show.legend = FALSE)+
  scale_colour_manual(values = c("#9467bd"),
                      name = "Treatment")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 3000),
                     breaks = seq(0, 3000, 1000),
                     labels = label_comma())+
    guides(colour = guide_legend(override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "F",
       x = "Year",
       y = "**TACE (n)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "none",
        legend.justification = c(0, 0.5),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"),
        legend.key.spacing.y = unit(0, "mm"))

p1_f
```

# AUS elastography

```{r}
df_test_mon_reg %>%
  filter(str_detect(PRO_name, "肝硬度|エラストグラフィ")) %>%
  count(PRO_name)
  
```

```{r}
df_test_mon_reg %>%
  filter(str_detect(PRO_name, "超音波")) %>%
  count(PRO_name, PRO_code)　
```


```{r}
# 160072210

df_us <- df_test_mon_reg %>%
  filter(PRO_code == "160072210") %>%
  mutate(TX = "US") %>%
  group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) 
```

```{r}
df_elast <- df_test_mon_reg %>%
  filter(str_detect(PRO_name, "肝硬度|エラストグラフィ")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "肝硬度") ~ "TE",
                        str_detect(PRO_name, "エラストグラフィ") ~ "USE")) %>%
  group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) 
```

```{r}
df_elast <- df_elast %>%
  group_by(YMD) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(TX = "Total") %>%
  bind_rows(df_elast)
```


```{r}
ts_img <- df_us %>%
  bind_rows(df_elast) %>%
  mutate(TX = factor(TX, levels = c("US", "Total","TE", "USE")))
```

```{r}
stl_img <- ts_img %>%
  group_by(TX) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_img
```


```{r}
stl_img <- stl_img  %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 

```

```{r}
stl_img %>%
  filter(anomaly == "Yes" & TX == "Total")
```


```{r}
stl_img <- stl_img  %>%
  mutate(across(c(observed, trend, season_adj), ~.x/10^3)) %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
    mutate(y_point = case_when(anomaly == "Yes" ~ observed,
                         .default = NA)) %>%
  mutate(y = case_when(
                       anomaly == "Yes" & TX == "Total"  ~ 35,
                       anomaly == "Yes" & TX == "TE" ~ 4,
                       anomaly == "Yes" & TX == "USE" ~ 0,
                      
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
p1_d <- stl_img   %>%
  filter(TX != "US") %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
  geom_point(aes(YMD, y_point, colour = TX),
             fill = NA,
             alpha = 0.8, size = 1,
             shape = 21, stroke = 0.75, 
             show.legend = FALSE)+
  scale_colour_manual(values = c("#8c564b",
                                 "#e377c2",
                                 "#17becf"),
                      labels = c("Total", "TE", "USE"),
                      name = "Elastography")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 50),
                     breaks = seq(0, 50, 10))+
    guides(colour = guide_legend(nrow = 3,
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "D",
       x = "Year",
       y = "**Elastography (×10<sup>3</sup>)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        legend.position = "inside",
        legend.justification.inside = c(0, 1),
        legend.position.inside = c(0.025, 1),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"),
      legend.key.height = unit(5, "mm"))

p1_d
```



```{r}
df_test_mon_reg %>%
  mutate(PRO_name = stri_trans_general(PRO_name, "Fullwidth-Halfwidth")) %>%
  filter(str_detect(PRO_name, "HB|HC|B型肝炎|C型肝炎|AFP|PIVKA"))　%>%
  count(PRO_code, PRO_name)
```


```{r}
# HBV

df_test_mon_reg %>%
  filter(PRO_code %in% c("160046810",
                         "160049210",
                         "160160350"))　%>%
  group_by(YEAR_str, PRO_name) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR_str, SUM, group = PRO_name, colour = PRO_name))+
  geom_line(linewidth = 0.3)+
  theme_classic()
```

```{r}
df_test_mon_reg %>%
  filter(PRO_code %in% c("160118510",
                         "160158450",
                         "160159750"))　%>%
  group_by(YEAR_str, PRO_name) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR_str, SUM, group = PRO_name, colour = PRO_name))+
  geom_line(linewidth = 0.3)+
  theme_classic()
```

```{r}
df_test_mon_reg %>%
  filter(PRO_code %in% c("160036710",
                         "160015610",
                         "160117110",
                         "160193310"))　%>%
  group_by(YEAR_str, PRO_name) %>%
  summarise(SUM = sum(VALUE)) %>%
  ggplot(aes(YEAR_str, SUM, group = PRO_name, colour = PRO_name))+
  geom_line(linewidth = 0.3)+
  theme_classic()
```


```{r}
# 160046810	HBs抗原定性･半定量
# 160049210	HBs抗原
# 160118510	HCV抗体定性･定量
# 160158450	HCV核酸定量
# 160159750	HCV核酸検出
# 160160350	HBV核酸定量

# 160015610 PIVKA-2
# 160117110	PIVKA-2半定量
# 160193310	PIVKA-2定量

# 160036710	α-ﾌｪﾄﾌﾟﾛﾃｲﾝ(AFP)
# 160162150	α-ﾌｪﾄﾌﾟﾛﾃｲﾝﾚｸﾁﾝ分画(AFP-L3%)

code_bm <- c("160046810",
               "160049210",
               "160118510",
               "160158450",
               "160159750",
               "160160350",
               "160015610",
               "160117110",
               "160193310",
               "160036710",
               "160162150")


df_bm <- df_test_mon_reg %>%
  filter(PRO_code %in% code_bm) %>%
   mutate(PRO_name = stri_trans_general(PRO_name, "Fullwidth-Halfwidth")) %>%
  mutate(TX = case_when(str_detect(PRO_name, "HBs抗原") ~ "HBsAg",
                         str_detect(PRO_name, "HCV抗体") ~ "HCVAb",
                         str_detect(PRO_name, "HCV核酸") ~ "HCV-RNA",
                         str_detect(PRO_name, "HBV核酸") ~ "HBV-DNA",
                        str_detect(PRO_name, "PIVKA-2") ~ "PIVKA-II",
                        str_detect(PRO_name, "AFP-L3") ~ "AFP-L3",
                        str_detect(PRO_name, "AFP") & !str_detect(PRO_name, "L3") ~ "AFP"
                        ))

```

```{r}
ts_bm <- df_bm %>%
  group_by(YMD, TX) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(YM = yearmonth(YMD)) %>%
  as_tsibble(key = TX, index = YM)

ts_bm 
```


```{r}
stl_bm <- ts_bm %>%
  group_by(TX) %>%
  time_decompose(target = SUM,
                 method = "stl") %>%
  anomalize(remainder,
            method = "gesd")

stl_bm
```


```{r}
stl_bm <- stl_bm  %>%
  mutate(YMD = rollforward(YMD)) %>%
  mutate(season_adj = observed - season) 

```

```{r}
stl_bm_sero <- stl_bm  %>%
  filter(TX %in% c("HBsAg", "HCVAb")) %>%
  mutate(across(c(observed, trend, season_adj), ~.x/10^6)) %>%
  mutate(label = case_when(anomaly == "Yes" ~ "*",
                         .default = NA)) %>%
    mutate(y_point = case_when(anomaly == "Yes" ~ season_adj,
                         .default = NA)) %>%
  mutate(y = case_when(anomaly == "Yes" & remainder > 0 & TX == "HBsAg"  ~ 0.6,
                       anomaly == "Yes" & remainder < 0 & TX == "HBsAg" ~ 0.6,
                       anomaly == "Yes" & remainder > 0 & TX == "HCVAb"  ~ 0.5,
                       anomaly == "Yes" & remainder < 0 & TX == "HCVAb" ~ 0.5,
                       .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                           anomaly == "Yes" & remainder < 0  ~ 180,
                          .default = NA))
```


```{r}
p1_b1 <- stl_bm_sero  %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
      geom_point(aes(YMD, y_point, colour = TX),
             alpha = 0.8, size = 1, stroke = 0.75,
             shape = 21, fill = NA,
             show.legend = FALSE)+
 scale_colour_manual(values = c("#d62728", "#1f77b4"),
                      name = "Test")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 1.5),
                     breaks = seq(0, 1.5, 0.5))+
    guides(colour = guide_legend(nrow = 2,
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "B",
       x = "Year",
       y = "**Viral marker (×10<sup>6</sup>)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification.inside = c(1, 0),
        legend.position.inside = c(1, 1/40),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.spacing = unit(0, "mm"),
        legend.key.height = unit(5, "mm"))

p1_b1
```

```{r}
stl_bm_nuc <- stl_bm  %>%
  filter(TX %in% c("HBV-DNA", "HCV-RNA")) %>%
  mutate(across(c(observed, trend, season_adj), ~.x/10^3)) %>%
  mutate(label = case_when(anomaly == "Yes"  ~ "*",
                         .default = NA)) %>%
    mutate(y_point = case_when(anomaly == "Yes"  ~ observed,
                         .default = NA)) %>%
  
  mutate(y = case_when(anomaly == "Yes" & TX == "HBV-DNA" ~ 110,
                       anomaly == "Yes" & TX == "HCV-RNA" ~ 10,
                         .default = NA)) %>% 
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
stl_bm_nuc %>%
  group_by(TX) %>%
  slice_max(YMD)
```

```{r}
y_nuc_pos <- stl_bm_nuc %>%
  group_by(TX) %>%
  slice_max(YMD) %>%
  ungroup() %>%
  summarise(MID = mean(trend)) %>%
  pull(MID)

y_nuc_pos
```


```{r}
p1_b2 <- 
  stl_bm_nuc %>%
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
      geom_point(aes(YMD, y_point, colour = TX),
             alpha = 0.8, size = 1,
             fill = NA, stroke = 0.75,
             shape = 21, 
             show.legend = FALSE)+
 scale_colour_manual(values = c("#d62728", "#1f77b4"),
                      name = "Test")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 200),
                     breaks = seq(0, 200, 50))+
    guides(colour = guide_legend(override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(
       x = "Year",
       y = "**Viral marker (×10<sup>3</sup>)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification.inside = c(1, 0.5),
        legend.position.inside = c(1, y_nuc_pos/200),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key.spacing.y = unit(0, "mm"),
        legend.box.spacing = unit(0, "mm"),
        legend.key.height = unit(5, "mm"))


p1_b2
```



```{r}
stl_bm_tm <- stl_bm  %>%
  filter(TX %in% c("AFP", "PIVKA-II")) %>%
  mutate(across(c(observed, trend, season_adj), ~.x/10^3)) %>%
  mutate(label = case_when(anomaly == "Yes"  ~ "*",
                         .default = NA)) %>%
  mutate(y_point = case_when(anomaly == "Yes"  ~ observed,
                         .default = NA)) %>%
  mutate(y = case_when(anomaly == "Yes" & TX =="AFP" ~ 240,
                       anomaly == "Yes" & TX == "PIVKA-II" ~ 80,
                         .default = NA)) %>%
  mutate(angle = case_when(anomaly == "Yes" & remainder > 0  ~ 0,
                       anomaly == "Yes" & remainder < 0  ~ 180,
                       
                         .default = NA))
```

```{r}
p1_c <- stl_bm_tm %>% 
  ggplot()+
    geom_rect(data = df_soe1,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe2,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
      geom_rect(data = df_soe3,
            aes(xmin = xmin,  xmax = xmax,
                ymin = ymin, ymax = ymax),
            fill = "#d9d9d9",
            inherit.aes = FALSE)+
  geom_line(aes(YMD, observed, group = TX),
            colour = "#7f7f7f",
            linewidth = 0.3) +
    geom_line(aes(YMD, trend, group = TX),
            colour = "black",
            linewidth = 0.4) +
  geom_line(aes(YMD, season_adj, group = TX, colour = TX),
            alpha = 0.8,
            linewidth = 0.5) +
      geom_point(aes(YMD, y_point, colour = TX),
                 fill = NA,
             alpha = 0.8, size = 1,
             shape = 21, stroke = 0.75,
             show.legend = FALSE)+
   scale_fill_manual(values = c("#d62728", "#1f77b4"),
                      name = "Test")+
 scale_colour_manual(values = c("#d62728", "#1f77b4"),
                      name = "Test")+
  scale_x_yearmonth(date_labels = "%Y",
               limits = c(as_date("2019-01-01"), as_date("2024-01-01") ),
               breaks = c(seq(as_date("2019-01-01"), as_date("2024-01-01"), by = "12 month")))+
  scale_y_continuous(limits = c(0, 250),
                     breaks = seq(0, 250, 50))+
    guides(colour = guide_legend(nrow = 2,
                                 override.aes = list(linewidth = 0.5,
                                                   alpha = 1)))+
  
  labs(tag = "C",
       x = "Year",
       y = "**Tumour marker (×10<sup>3</sup>)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification.inside = c(1, 0),
        legend.position.inside = c(1, 1/40),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.box.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.key.spacing.y = unit(0, "mm"),
        legend.box.spacing = unit(0, "mm"),
        legend.key.height = unit(5, "mm"))

p1_c
```

```{r}
p1 <- p1_a1 + p1_a2 +
  p1_b1 + p1_b2 +
  p1_c + p1_d + 
  p1_e + p1_f  +
  p1_g1 + p1_g2 +
  plot_layout(ncol = 2,
              nrow = 5,
              height = c(2, 4, 4, 4, 4)) &
  theme(axis.title.x = element_text(size = 8, 
                                    colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        legend.box.spacing = unit(1, "mm")
        )

ggsave("../figure/Fig2.pdf", p1, width = 175, height = 235,
       device = cairo_pdf,
       unit = "mm")
```
